README.md

Add getting in touch section to README
- See why
- :eyes:

[docs] Add getting in touch section

---

packages/snack-sdk/README.md

[docs] Fix snack-sdk API reference link

---

.eslintignore
package.json
packages/snack-sdk/.eslintignore
yarn.lock

[style] Upgrade & fix linting

---

.github/workflows/snack-sdk.yml
.prettierrc

[ci] Run CI workflows on workspace changes

---

.github/workflows/snack-sdk.yml
.prettierrc

[ci] Run snack-sdk workflow on workspace changes

---

.eslintignore
.eslintrc.base.js
.eslintrc.js
.prettierignore
package.json
packages/snack-sdk/.eslintignore
packages/snack-sdk/.eslintrc.js
packages/snack-sdk/src/DependencyResolver.ts
packages/snack-sdk/src/DevSession.ts
packages/snack-sdk/src/Logger.ts
packages/snack-sdk/src/Session.ts
packages/snack-sdk/src/State.ts
packages/snack-sdk/src/__mocks__/pubnub.ts
packages/snack-sdk/src/__tests__/files-test.ts
packages/snack-sdk/src/__tests__/sdkversion-test.ts
packages/snack-sdk/src/sdks/index.ts
packages/snack-sdk/src/transports/CodeMessageBuilder.ts
packages/snack-sdk/src/transports/Protocol.ts
packages/snack-sdk/src/transports/Transport.ts
packages/snack-sdk/src/transports/worker.example.ts
packages/snack-sdk/src/utils.ts
packages/snack-sdk/tsconfig.json
yarn.lock

Stricter linter rules and prepare tooling for snack web.
- Update linter config
- Remove global `yarn lint`
- Fix newly detected lint warnings

[style] Enforce stricter linting rules

---

docs/url-query-parameters.md

[docs] Add `verbose` and `hideQueryParams` url arguments

---

.eslintrc.base.js

[style] Update eslint react version to 16.8

---

website/deploy/base/kustomization.yaml

Fixes https://github.com/expo/snack/actions/runs/530433042

[ci] Fix website workflows after snack.env file removal

---

.envrc
CONTRIBUTING.md
README.md
website/README.md

Update instructions for running the website independently.

[docs] Update website README/docs

---

website/package.json
yarn.lock

Should fix https://github.com/expo/snack-web/pull/36
- Update terser plugin
- Ran `yarn start` and verified the web-app loads correctly

[website] Update terser plugin

---

website/src/client/components/ServiceWorkerManager.tsx

Fixes #65
- Add z-index to the right place

[website] Fix titlebar buttons overlapping update notification

---

CONTRIBUTING.md

I have noticed two typos in the CONTRIBUTING.md file.
I have fixed the problem by correcting the typos.
Read the file 🙂

[docs] Fix typos in CONTRIBUTING.md

---

README.md

[docs] Add ReactEurope 2017 talk

---

website/src/client/components/App.tsx
website/src/client/components/AppDetails.tsx
website/src/client/components/DeviceInstructions/AccountTab.tsx
website/src/client/components/DeviceInstructions/DeviceIDTab.tsx
website/src/client/components/DeviceInstructions/QRCodeTab.tsx
website/src/client/components/DevicePreview/MyDeviceFrame.tsx
website/src/client/components/EditorView.tsx

Follow up to #71, fix several missing "Expo app" instances and some improvements here and there.

[website] Update missing Expo app references -> Expo Go

---

packages/snack-sdk/CHANGELOG.md
packages/snack-sdk/src/DependencyResolver.ts
packages/snack-sdk/src/Session.ts
packages/snack-sdk/src/__tests__/__snapshots__/dependencies-test.ts.snap
packages/snack-sdk/src/__tests__/dependencies-test.ts

[sdk] Fix dependencies with subpath not using bundledNativeModules.json

---

packages/snack-sdk/README.md

[docs] Fix typo in snack-sdk readme

---

.github/workflows/snack-proxies.yml
.github/workflows/snack-sdk.yml
.github/workflows/website-production.yml
.github/workflows/website-staging.yml

[ci] Use node 12 and dont run production workflows on PRs

---

.github/workflows/tools.yml

Also run tools GitHub action on pull-requests, but don't decrypt secrets from forked repos

[ci] Run tools workflow on pull requests

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/questions.yml

Just your friendly neighborhood Spiderman bringing the Issue Form syntax up to date with the latest changes as described in: https://gh-community.github.io/issue-template-feedback/changes/
I work on the team that's building issue forms 😄 thanks for testing it out for us!
:shipit:

[docs] Update GitHub Issue Forms to use the new syntax

---

bin/prune-gcr

Add `prune-gcr` script needed for Snackager.

[tools] Add prune-gcr script

---

website/deploy/production/deployment-replicas.yaml

Discussed this in the response of [issue #1449](https://expo.pagerduty.com/incidents/PJJNR3W).
- Updated `replicas` to `4`
- ~~Added minimum replicas (as per @quinlanj's suggestion)~~
- Validate in GCP Kubernetes

[website] Increase infra to minimum of 4 pods

---

snackager/src/types.ts
snackager/src/utils/resolveDependencies.ts

[snackager] Remove obsolete unimodulePeerDependencies field

---

.github/workflows/appetize.yml

See #194, this is a full refactor of that version.
See #194
See #194

[ci] Add appetize workflow to check and deploy new simulator builds

---

website/src/server/components/AmplitudeDocumentComponent.tsx

Right now, it doesn't capture all referrals.
See https://developers.amplitude.com/docs/javascript#track-referrers
Deploy and see if it improves.

[website] Properly initialize Amplitude to include referrals

---

.github/CODEOWNERS

Remove ijzerenhein as codeowner

---

runtime/src/Messaging.web.tsx

Refs:
* https://github.com/expo/snack/pull/160#issuecomment-1003700383
CC: @Tozare
This PR adds new Sizze subdomain to allow list for the Snack web-player.
Unable to test.

[runtime] allow web-player for new Sizze domain

---

packages/snack-sdk/src/DependencyResolver.ts

- [TS 4.4.4 behavior](https://www.typescriptlang.org/play?ts=4.4.4#code/MYGwhgzhAEAqkGsCyYB2YDmBTATtA3gFDQnQAuiEAXAdANoJYCeNEZOAlqhgLo0AKOAPYBbDhCwAeNEwB80AL7QAvAQUBuQsVJswOMvAgIAFOhFZW7LhgA00AFZCARgOFiJ01HICUBbaVIyAAtxADoKIwg6MyweFQdnTQCFLQCgyEMTGMtObl8iAICAeiLoAElUchCYDgAzaF0yLHNUMmgnLBAhAHc7bqwHAFc2aG60NrIhaAATLCbgNrrRgfSANwGwaBwsDHEm7emEp2haoTxgsDaY0P9CktIAWjgmAAcsAGVgThe2gBZQgDMoQArDMhFgYKghBNOBhsHgZNBcMIcBBbsVSiQnrBXh8vhwftB-sTyLD4TAAESwd4AJgAHAAGACMFOgT1OOAw0PIUzAYw4bRebnEWHRpBKYpI91g1XaWDWHDOJzcRNCJIkzRg-Q4OGmdg6wDAwwG-VG4x5Jy4hyEg0W9WCuA222giO2uzYjsOEQQEBuhXFpRlAyFohFWwhgxAbSVjWG0HE8Zw2xAWFW4zsDug5jQ1mgIA4EPjlQpCYdzs2IfcAyVULIFMl8fqxmCYW9URiPHyDYC2zIgxwlXYgywSX9ilSY+lsoTtS4A2CNowQTsNrIEA4s2gQnqaEbDQoTRaZAbvf7lQAhOeW7629EwOYeKP-VOEwmwCAIFNZ6gsHZU1hKm6AUQkqXclkaZoAOPMdoHuJZTHvAYuCqV …

[snack-sdk] Explicitly convert promise to boolean to check existence

---

.github/workflows/snackager-production.yml
.github/workflows/snackager-staging.yml
.github/workflows/website-production.yml
.github/workflows/website-staging.yml

I don't know, ask https://github.com/GoogleContainerTools/skaffold/pull/7089#discussion_r845391034
- Moved all `skaffold deploy --status-check` to `skaffold deploy --status-check true`
- See if staging images can be deployed

Fix skaffold deploy status check flag

---

.github/actions/setup-google-cloud/action.yml
.github/workflows/snackager.yml
.github/workflows/website.yml

All traffic has been switched to the services running in the general-central cluster.

[CI] End rollouts to old cluster

---

website/src/client/components/Publish/ModalPublishToProfile.tsx

Fixes #340 
Changed the text your to you

[website] Fix typo in save snacks dialog

---

packages/snack-content/src/defaults.ts
packages/snack-sdk/src/__tests__/__snapshots__/dependencies-test.ts.snap
packages/snack-sdk/src/__tests__/__snapshots__/devsession-test.ts.snap
snackager/src/__integration-tests__/__snapshots__/git.test.ts.snap

All is well for this one! Time to switch :)
See commits
See staging & production right now.

Set Expo SDK 46 as default

---

snackpub/package.json
snackpub/src/Env.ts
snackpub/src/RedisAdapter.ts
snackpub/src/TypedEventEmitter.ts
snackpub/src/index.ts
yarn.lock

enhance redis integration for snackpub
- make sure to use redis adapter in production env
- handle redis connection errors and reconnection
ci passed

[snackpub] redis integration enhancement

---

snackpub/scripts/deploy.sh
website/src/server/utils/getSplitTests.tsx

snackpub works good so far, let's rollout more traffic
- increase the traffic from 10% to 50%
- increase the cloud run max capacity 
ci passed

[snackpub][website] increase more snackpub traffic and capacity

---

website/src/server/utils/getSplitTests.tsx

everything looks good and it's a further step to migrate snackpub
now we will have 100% traffic to snackpub
- snackpub + pubnub 50%
- snackpub only 50%
deploy and monitor the traffic

[website] migrate more snackpub traffic

---

website/src/server/utils/getSplitTests.tsx

everything works fine. it's time to fully roll out snackpub.
100% snackpubOnly
deploy and see what's going

[website] fully rollout snackpub

---

.github/workflows/website.yml

See the failure of #408
Disabled the failing job by commenting out.
Rebase PR #408, check if it passes.

chore(website): disable random failing website config check

---

website/src/client/components/NonExistent.tsx

Fixes ENG-7978
Replace Router DOM Link with bare HTML anchor.
The change has been tested by running Snack stack locally.

[website] fix 404 home link

---

snackager/k8s/base/deployment.yaml

[snackager] Remove volume mount.

---

website/src/client/utils/projectNames.tsx

Addition to PR #447
- [Googled rainbow colors](https://www.npg.org.uk/learning/digital/family-activities-playful-portraits/dorothy-hodgkin/6-8-years-colours-of-the-rainbow#:~:text=The%20colours%20of%20the%20rainbow,red%20items%20can%20you%20find%3F)
- Added rainbow colors
See staging.

fix(website): ensure unique project names by adding rainbow colors

---

.github/workflows/appetize-deploy.yml
.github/workflows/appetize-validation.yml
.github/workflows/runtime.yml

Infrastructure update.
- Updated all screts to the proper secret name
- TBD

refactor(ci): update secrets to the rotated key names

---

runtime/vendor/reanimated-plugin.js

This is the plugin that runs on user code itself.
- Followed the same steps as previous vendoring
See staging, will deploy once everything is done.

chore(runtime): upgrade vendored `react-native-reanimated` plugin to `3.6.1`

---

packages/snack-content/src/defaults.ts
packages/snack-content/src/sdks/index.ts
packages/snack-content/src/sdks/types.ts
packages/snack-sdk/src/__fixtures__/snackager.ts
packages/snack-sdk/src/__tests__/__snapshots__/dependencies-test.ts.snap
packages/snack-sdk/src/__tests__/dependencies-test.ts
packages/snack-sdk/src/__tests__/save-test.ts
website/src/client/configs/constants.tsx
website/src/client/configs/sdk.tsx

Split out from #523
- See changes
TBD, see staging

refactor: drop Expo SDK 47

---

packages/snack-runtime/src/transports/RuntimeTransportImplWebPlayer.ts
runtime/src/transports/RuntimeTransportImplWebPlayer.ts

Add new Codecademy domain as allowed domain.
Added to allowlist for Snack communication
Check with Codecademy to see if requests are coming through

chore(runtime): add new codecademy domain as allowed origin
