expo/snack

- packages/snack-sdk/CHANGELOG.md
- packages/snack-sdk/package.json
Publish initial snack-sdk@3.
- Update version
- Update changelog
- :eyes:
> [sdk] Publish initial snack-sdk@3 release

- docs/snack-sdk-api/README.md
- docs/snack-sdk-api/classes/snack.md
- docs/snack-sdk-migration.md
- docs/snack-sdk.md
- packages/snack-sdk/CHANGELOG.md
- packages/snack-sdk/src/__tests__/sdkversion-test.ts
- packages/snack-sdk/src/index.ts
- packages/snack-sdk/src/sdk.ts
- packages/snack-sdk/src/sdks/features.ts
- packages/snack-sdk/src/sdks/types.ts
- packages/snack-sdk/src/types.ts
- packages/snack-sdk/typedoc.json
Add `isFeatureSupported` method for checking whether older SDK support certain features such as "TYPESCRIPT". This feature is needed by www in order to migrate to snack-sdk 3.
- Add `isFeatureSupported` global method
- Add tests for `isFeatureSupported`
- Update docs
- Updated Migration Guide
- Fixed SDKVersion type not documented
- Updated changelog
- `yarn lint`
- `yarn build`
- `yarn test`
> [sdk] Add `isFeatureSupported` helper function

- docs/snack-sdk-api/README.md
- docs/snack-sdk-migration.md
- packages/snack-sdk/CHANGELOG.md
- packages/snack-sdk/src/__tests__/dependencies-test.ts
- packages/snack-sdk/src/index.ts
- packages/snack-sdk/src/sdk.ts
Add `standardizeDependencies` method for converting older Snack `dependencies` formats. This feature is needed by www in order to migrate to snack-sdk 3.
- Add `standardizeDependencies` global method
- Add tests for `standardizeDependencies`
- Update docs
- Updated Migration Guide
- Updated changelog
- `yarn lint`
- `yarn build`
- `yarn test`
> [sdk] Add `standardizeDependencies` helper function

- packages/snack-sdk/CHANGELOG.md
- packages/snack-sdk/src/DependencyResolver.ts
- packages/snack-sdk/src/Session.ts
- packages/snack-sdk/src/__tests__/__snapshots__/dependencies-test.ts.snap
- packages/snack-sdk/src/__tests__/dependencies-test.ts
Fixes https://forums.expo.io/t/cannot-open-old-snack/47209/3, which was caused by the snack-sdk modifying the initial dependencies object and setting an error status on the faulty dependency. This in turn caused the `__INITIAL_DATA` obect to be modified and serialised to fail because the Error object could not be serialised.
The faulty dependency was indeed not really invalid. It was a scoped dependency name with a subpath, but that particular case was not correctly supported.
- Fix (prevent) modification of initial dependencies object
- Add support for scoped dependency names with subpaths (eg. `@scope/name/subpath`)
- Add tests for scoped dependency names
- Verified modification fix in snack-web and confirmed it works
> [sdk] Fix dependencies object modification & scoped dependency names

- .github/workflows/snack-sdk-legacy.yml
- .github/workflows/snack-sdk.yml
Use default working directory in github actions to simplify definition file.
> [ci] Use default work-dir for sdk actions

- .envrc
- .github/workflows/tools.yml
- bin/lock
- bin/unlock
Add support for git-crypt. This allows the use of `lock` and `unlock` commands to lock/unlock secrets.
- Add `lock` and `unlock` scripts to `/bin`
- Add path to `/bin` to env
- Add GH action to verify unlocking of secrets in CI
- Go to root of repo
- `direnv allow`
- `unlock` runs
- `lock` runs
> [tools] Add git-crypt

- packages/snack-sdk/src/index.ts
- packages/snack-sdk/src/types.ts
To allow TypeScript projects to import the sources directly.
> [sdk] Export types using type keyword

- .github/workflows/website-production.yml
- .github/workflows/website-staging.yml
Don't Notify slack when merely production build succeeds, but only when it fails or is deployed to production.
Also fixes the github workflows not re-run when changing them
> [ci] Only notify slack when deploying website

- CONTRIBUTING.md
Adds missing steps that are needed by contributors to start the Snack development environment locally.
> [docs] Add direnv and chalet instructions

- website/resources.json
Fixes https://github.com/expo/snack-web/pull/43
- Update resource urls to jsdelivr
- Scanned code for any other cloudflare usage, but didn't find any
- Confirmed locally that all resources url still load
> [website] Use jsdelivr CDN for resources

- ecosystem.config.js
- website/src/server/index.tsx
Fixes website app not recompiling code changes when started with `yarn start` from the root.
- Add watch config for pm2
- Add logs to measure website startup
> [website] Fix website watcher and add start logs

- website/src/client/components/App.tsx
- website/src/client/components/DeviceInstructions/WhyNoQrBanner.tsx
- website/src/client/components/DevicePreview/MyDeviceFrame.tsx
- website/src/client/components/EmbeddedEditorView.tsx
- website/src/client/components/shared/OpenWithExpoButton.tsx
Rename "Expo Client" to "Expo Go"
> [website] Rename Expo Client -> Expo Go

- packages/snack-sdk/src/__fixtures__/bundledNativeModules.json
- packages/snack-sdk/src/sdks/index.ts
Updates the SDK 40 version, which was still set to beta.2 instead of using the latest version.
> [sdk] Update SDK 40 & 39 versions

- website/src/client/components/Import/ImportRepoModal.tsx
- yarn.lock
Fixes the Git Import button which is not enabled when entering the repo location through the "advanced" options.
- Fix faulty button disabled prop
- Rename "master" to "main"
- Verified button is enabled and works using Git url
- Verified button is enabled and works using advanced Repo url
> [website] Fix import button and rename to “main”

- website/src/client/components/DependencyManager.tsx
- website/src/client/components/EditorView.tsx
- website/src/client/utils/fileUtilities.tsx
Fixes dependency error on `react-test-renderer` and linter warnings/errors on tests.
*see `react-test-renderer` error and `it` & `define` warninga*
- Exclude test files from dependency scanning
- Exclude test files from linting
- After changes errors and warnings in the tests are gone
> [website] Fix dependency and linter warnings on test files

- packages/snack-sdk/jest.config.js
Otherwise `yarn test` also tests the output of the build folder, which might be old and tends to produce ver vague errors.
> [sdk] Fix `yarn test` when build folder exists

- packages/snack-sdk/src/DevSession.ts
- packages/snack-sdk/src/Session.ts
- packages/snack-sdk/src/__tests__/devsession-test.ts
- packages/snack-sdk/src/__tests__/save-test.ts
- packages/snack-sdk/src/types.ts
- packages/snack-sdk/src/utils.ts
Adds basic support for `user: { accessToken: '...' }` to programmatically interact with stored Snacks.
- Added helper for the `Expo-Session` or `Authorization: bearer ...` headers.
- Added tests for devsession to send authenticated requests
- Create a new snack
- Add `snack.setUser({ accessToken: '...' })`
- Save the snack
- Snack should be saved on account by only using the access token
> [sdk] Add support for access token authentication

- .github/workflows/website-staging.yml
- .github/workflows/website.yml
- website/deploy/production/snack.env
- website/deploy/staging/snack.env
Adds a GitHub action workflow for the `website` which runs the build, tests and linter without the need of any secrets. This is intended for PRs that are created from external forks and don't have access to the secrets.
> [ci] Add website workflow for external PRs

- website/src/client/components/QRCode.tsx
Currently it's possible to use selection to make visible the Screen Reader only URL which is a part of `QRCode` component.
This PR includes small CSS fix (utilizing `user-select`) which fixes the issue, additionally I have extracted the existing inline styles from the component and replaced comment just by setting self-explanatory name to the style variable name.
I have tested the changes on `localhost` using existing `dev` pipeline.
> QRCode: remove ability to select screen reader only URL

- website/src/client/components/ThemeProvider.tsx
Currently the Dark Mode hover color is quite contrasting, in comparison to the hover color in Light Mode. This also contributes to the lower readability of few UI elements while active or hovered (for example `EditorFooter` sections):
In this PR I have changed the `hover` color value in `darkColors` to the shade a step darker, which improve a bit the readability and makes closer match to the Light Theme hover effect.
Additionally I have added the `popup` shadow back in the Dark Mode. Since shadows are based on pure black color (`0 2px 6px rgba(0,0,0,0.15)`) I see no backdrafts from turning them back on. The current value isn't ideal (shadows are not that prominent as in Light Mode), but they helps a bit distinguish UI elements in certain situations, few examples:
Maybe in Dark Mode popups …
> dark mode: tweak hover color and add popup shadows

- website/src/client/components/EditorTitleName.tsx
Currently the "Edit details" button in the details popup it's hard to distinguish from  the regular text in Dark Mode. Additionally, despite being a clickable element, it doesn't contains the `hover` style. There is also a small issue in the `:active` state, where top border becomes `black` (at least on Windows Chrome).
This PR tweaks a bit the appearance of "Edit details" button - switches the text color to `primary` (which affects only Dark Mode), add basic `hoover` color and rewrites the border style which seems to be the culprit for the border issue.
P.S. The `hover` effect readability in Dark Mode should improve after #93 merge.
I have tested the changes on `localhost`.
> "Edit details" popup button style tweaks

- package.json
- packages/snack-proxies/package.json
- packages/snack-term/package.json
- packages/snack-term/src/Terminal.tsx
- website/deploy/development/snack.env
- website/package.json
Improves `snack-term` to handle stderr and failed process startups. Also removes `strip-ansi` which was not used. Additionally this PR makes various yarn scripts consistents and cleans up no longer needed commands.
> [tools] Terminal updates & cleaner logging

- docs/hosts-ports.md
- packages/snack-proxies/src/index.ts
- website/README.md
- website/deploy/development/snack.env
- website/src/client/components/App.tsx
- website/src/client/types.tsx
- website/src/client/utils/reloadURL.tsx
Adds a proxy for Snackager. The proxy allows for seeing the requests sent to Snackager and automatically switches to the local running Snackager when possible. This removes the need for the `local_snackager` query argument in the `website`.
- Add Snackager proxy
- Update docs
- Remove `local_snackager` query arg for website
```
│ $ ts-node-dev --inspect=9221 src/index.ts                                                                                                                                                                                   │
│ [INFO] 15:48:37 ts-node-dev ver. 1.1.1 (using ts-node ver. 9.1.1, typescript ver. 4.1.3)                                                                                                                                    │
│ Starting "expo-www" …
```
> [proxy] Add Snackager proxy

- website/package.json
- yarn.lock
Upgrades babel to the latest version.
- `yarn start` runs and site works as expected
- Verified output of `build` and there were no differences at all
- Verified output of `dist` and there was no difference in total size
> [website] Upgrade babel

- .editorconfig
- .gitattributes
Currently, on the Windows, IDEs and ESLint want to reformat EOL characters across all the repository files. This is due to OS differences in handling files.
To fix this I have setup:
* `.gitattributes` file with basic configuration according to - https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings#per-repository-settings
* `.editorconfig` file, unfortunately it was also required, `.gitattributes` was not enough to get rid of the warnings - RN uses the same approach in theirs repository - https://github.com/facebook/react-native/blob/master/.editorconfig . You can read amore about `.editorconfig`  on the official website - https://editorconfig.org/.
To ensure backward compatibility and to remove the need to reformat all the repository files I have stick to …
> fix line endings issues on Windows

- website/src/client/components/Shell/EmbeddedFooterShell.tsx
- website/src/client/components/shared/ToggleButtons.tsx
Currently (like for switch) the OS tabs are using `selected` color, so in Dark mode it becomes white (in comparison to the purple in the Light Mode).
Also the OS tabs in the Embedded Snack are affected. Not only the color is not that readable, but the tabs are also clipped at the bottom (especially visible in the Dark Mode).
This small PR changes the tabs background and border colors to `primary` which make the purple in the Dark Mode too.
Additionally I have fixed the clipping issues by removing the hardcoded height of `EmbeddedFooter`. This change results in even (`4px`) padding from all the sides, which improves the overall appearance and fixes the clipping.
Snack run on the `localhost`.
> improve OS tabs appearance in Dark Mode, improve EmbeddedFooter

- website/src/client/components/Editor/themes/monaco-overrides.tsx
- website/src/client/components/EditorFooter.tsx
- website/src/client/components/KeyboardShortcuts.tsx
- website/src/client/components/shared/ContextMenu.tsx
- website/src/client/components/shared/ShortcutLabel.tsx
- website/src/server/pages/Document.tsx
Currently, depending on the place, keyboard shortcuts could look a bit differently. Not all of them have the same color shade or were using same font-family. Also differentiating the appearance more between the label and shortcut could help some users better distinguish bot parts of item/menu.
Also I was thinking about, and testing, addition of "button frame" in two forms:
* regular keyboard button (border + small radius + double border/box-shad at the bottom)
* pill style button (border + 50% radius)
But I wasn't happy with any of this solutions. They have made the shortcuts eye-heavy and they draw too much of user attention, so I have completely opt-out adding any frame in this changeset (but the refactored code should make a bit easier future experiments).
This PR aims to unify the …
> [website] Unify keyboard shortcuts and appearance

- .github/workflows/snackager-production.yml
- .github/workflows/snackager-staging.yml
Fixes `prune-gcr` for the Snackager production github action.
- Install python 2.7
- Execute `prune-gcr` from correct working directory
- Add `gcr-prune` dry-runs for staging and PRs
- Staging and production CI actions run successfully
> [ci] Fix prune-gcr for Snackager CI actions 53f0682

- website/src/client/components/App.tsx
- website/src/client/components/EditorView.tsx
- website/src/client/components/EditorViewProps.tsx
Shows a downgraded message when requesting an Expo SDK version that is not yet supported (eg. 41)
- Add downgraded message
- Cleanup banner code a bit
- Verified locally
> [website] Show downgraded message when newer Expo SDK is requested

- packages/snack-sdk/src/__fixtures__/snackager.ts
- packages/snack-sdk/src/__tests__/__snapshots__/dependencies-test.ts.snap
- packages/snack-sdk/src/__tests__/__snapshots__/devsession-test.ts.snap
- packages/snack-sdk/src/__tests__/dependencies-test.ts
- packages/snack-sdk/src/__tests__/devsession-test.ts
- packages/snack-sdk/src/__tests__/sdkversion-test.ts
- packages/snack-sdk/src/__tests__/url-test.ts
- packages/snack-sdk/src/defaultConfig.ts
- packages/snack-sdk/src/sdks/index.ts
- packages/snack-sdk/src/sdks/types.ts
This is a stacked PR on top of #123, but for the `snack-sdk` instead. 
- Dropped support for SDK 37
- Switched to SDK 41 by default
- Updated all tests and snapshots to include 38 or higher
- `$ yarn test`
- Make sure staging is working as expected using the test plan from #121
> [snack-sdk] Release Expo SDK 41

- snackager/src/bundler/externals.ts
Add `moti` / reanimated 2 support to Snack.
Context: https://twitter.com/cedricvanputten/status/1384532812720660482?s=20
Try adding `moti` to snack.
cc @byCedric
> [snackager] Add react native render shim to external list

- snackager/src/__integration-tests__/bundleAsync.ts
With the shim addition from PR #126, I noticed the Snackager bundle snapshots raising false errors.
What's (probably) happening here is that the lock file, generated on macOS, contains platform incompatible modules for Linux.  This should not stop Yarn from installing in our test, even though we run on Linux.
- Added `--ignore-platform` in our tests when a lock file is used
See if CI passes.
> [snackager] Add Yarn platform ignore flags in CI

- website/src/client/components/EditorPanelLogs.tsx
- website/src/client/components/shared/CollapsibleObject.tsx
Currently logging long value, like arrays or objects keys results in vertical scroll in the Logs panel and shifted a bit content.
This PR fixes the issues by adding few CSS lines. 
~Unfortunately `aphrodite` [package types](https://github.com/Khan/aphrodite/blob/master/typings/css-properties.d.ts#L1740) do not list `whiteSpace: 'break-spaces` option so I had to add the line ignore. `break-spaces` is not that new property and it's [widely supported](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space), but the `aphrodite` seems to be no longer maintained - types definitions are 3+ years old.~
After testing a bit, it looks like that `whiteSpace: 'normal'` yield the same layout result as `'break-spaces'`, so I have switched the values to avoid TS ignore comment. 🙂 
Running Snack …
> [website] Fix logs panel text wrapping

- README.md
- docs/expo-sdk-upgrade.md
Add documentation that condenses all the instructions needed to upgrade Snack to a new Expo SDK. The upgrade to SDK 41 can be used to verify the instructions and update them where needed.
- Add `./docs/expo-sdk-upgrade.md`
- Add hidden internal reference in README.md
I've done my best to include all necessary steps in the document. We should verify by letting someone else perform the upgrade and make adjustments to the instructions accordingly. @byCedric :)
> [docs] Add SDK upgrade manual (instructions for maintainers)

- snackager/src/cache-busting.ts
- snackager/src/config.ts
- snackager/src/utils/fetchBundle.ts
The `react-native-reanimated2` native bundles are invalid because they internalized `react-native/Libraries/Renderer/shims/ReactNative`. This was fixed by PR #126 This PR adds support for package specific cache-busting to Snackager and invalidates the current caches for `react-native-reanimated2`.
- Extend the cache-handle to include an additional suffix (e.g. `-1`) to invalidate current caches
- Bust cache for `react-native-reanimated`
- Verified locally
- `yarn start`
- Open website and add `react-native-reanimated` to the dependencies
- Watched how Snackager rebuild the package
- Removing and re-adding the package returned the newly cached package
> [snackager] Add package specific cache-busting

- snackager/src/cache-busting.ts
- snackager/src/utils/packageBundle.ts
Fixes `moti` not working on Snack because the `worklets` inside it are not compiled using the reanimated2 plugin.
- Run reanimated2 plugin on all packages that have `react-native-reanimated` as a dependency (or detected external)
- Bust cache on `moti` package
- Verified locally and confirmed the moti example works on both web and ios
> [snackager] Fix packages using reanimated 2

- website/src/client/configs/sdk.tsx
Sets Expo SDK 41 as the default SDK for the Snack website.
- See why
- Verified reanimated2 and moti@0.10.1 examples work on SDK 41 (both web and native)
> [website] Use Expo SDK 41 by default

- packages/snack-term/src/Terminal.tsx
- packages/snack-term/src/index.tsx
Terminal app overflows past the bottom when logs wrap and occupy multiple lines. This PR also adds a link to `snack.expo.test` at the bottom to quickly open the Snack website.
> [tools] Fix terminal line wrapping

- website/deploy/production/ingress-spec.yaml
- website/deploy/staging/ingress-spec.yaml
We want to deploy Snack on snack.expo.dev so that it can share cookies with users logged in on expo.dev
- added new host entries to staging and production ingress config.
After this change, snack.expo.dev should work and render the snack UI
> [k8s] deploy snack on expo.dev

- website/src/client/components/Import/ImportFilesManager.tsx
Right now, users can only upload JS files through the "Import files" modal. I don't think we should limit it to JS only, as users should be able to upload images and maybe JSON/txt files too.
Removed the `accept="js"` from the file import modal.
- See if we can upload more types of files after this change, e.g. assets and code.
> [website] Remove file import JS limitation

- docs/expo-sdk-upgrade.md
- docs/hosts-ports.md
- packages/snack-proxies/src/index.ts
- runtime/__internal__/DEPLOYING.md
- runtime/src/App.tsx
- website/deploy/staging/snack.env
- website/skaffold.yaml
- website/snack-embed.html
- website/src/client/components/App.tsx
Migrates all staging URLs (with exception of Snackager) to `.dev`. instead of `.io`. This PR serves as a test to verify all Snack services work correctly on `.dev` prior to migrating production to `.dev`.
- Update all staging URLs to `.dev`
- Fix runtime preview uploads which always uploaded to production and never to staging
- Snackager URLs are unchanged
- Verified locally on `expo.test`. Attempted login and confirmed local login works correctly and no longer redirects.
- Verified runtime `uploadPreview` now uses the correct staging URL and succeeds
> [snack] Migrate staging urls to .dev

- website/src/client/components/Import/ImportFilesManager.tsx
- website/src/client/components/Import/ImportRepoModal.tsx
- website/src/client/utils/convertDataTransferItemsToFiles.tsx
- website/src/client/utils/fileUtilities.tsx
This PR makes several improvements to importing files and repositories.
Replaces #154
- Indicate that only Public git repo's are supported
- Display error-code from Snackager when git import fails
- Show size for file when importing through drag & drop
- Layout improvements to import files modal
- Drag & drop a file onto Snack and confirm size is shown
- Drag & drop `.json` file and confirm it was imported as a code file (and not an asset)
- Import invalid Git repo and confirm error is shown (`https://github.com/ide/love-languages/tree/main/app`)
> [website] Import files/repo improvements

- runtime/src/Analytics.tsx
- runtime/src/App.tsx
- runtime/src/Console.tsx
- runtime/src/Messaging.tsx
- runtime/src/Messaging.web.tsx
- runtime/src/NativeModules/getDeviceIdAsync.tsx
- runtime/src/NativeModules/getDeviceIdAsync.web.tsx
Removes the deprecated `Constants.installationId` and replaces it with a persisted randomly generated Id.
- Use expo-random to generate a one time random id (hex 32 chars) and store in async/local-storage
- Remove `installationId` usage and warning
- Loaded Snack runtime into Expo Go (iOS) and logged device-id to console
- Confirmed that the device-id remains the same after reloading the Snack runtime (by shaking and reloading)
- Loaded Snack web-player into the Snack website (using the localhost option)
- Confirmed that the device-id remains the same when refreshing the web-player
> [runtime] Remove installationId

- runtime/src/BarCodeScannerView.native.tsx
- runtime/src/aliases/common.tsx
Remove usage of deprecated `expo-permissons` API.
- Replace expo-permissions by new requestPermissions API in barcode-scanner
- Add note that `expo-permissions` should be removed entirely in SDK 42
- `yarn lint && yarn tsc`
- `yarn start`
- Uninstalled Expo Go on iPhone
- Installed Expo Go and loaded Snack runtime using qr-code
- Watched Expo Go present the camera permissions prompt
> [runtime] Remove expo-permissions usage

- runtime/src/Messaging.web.tsx
To allow running the Snack web-player on the sizze.io domain.
@Tozare
- Add `https://dashboard.sizze.io` to list of allowed domains
- Unable to test, needs to be performed by sizze.io after deployment
> [runtime] Allow web-player on sizze domain

- snackager/src/__integration-tests__/__snapshots__/bundler.test.ts.snap
- snackager/src/bundler/externals.ts
- snackager/src/cache-busting.ts
Fixes web-bundles that use `react-dom` directly such as `@material-ui` (and indirectly `@drafbit/ui`). In these cases `react-dom` was falsly included **inside** the bundle which conflicted with `react-dom` which was already included in the Snack runtime using `react-native-web`. This PR resolves the problem in Snackager by ensuring that `react-dom` is always externalized.
**After the fix**
- Always externalize `react-dom`
- Invalidate cache for `@draftbit/ui`
- Update tests
- Bump cache-bust number for `@drafbit/ui`
- `yarn start`
- Open `http://snack.expo.test/` and import Snack from production: https://snack.expo.io/@peterpme/(draftbit)-onboarding---kid-info
- Load web-preview and click on date (see screenshot in #why)
- Run `yarn test` to verify all tests succeed
> [snackager] Fix react-dom not externalized in web-bundles

- website/src/expo-dev-migration/index.ts
- website/src/server/routes.tsx
The snack.expo.io -> snack.expo.dev redirect isn't working as expected in staging, so I want to learn more about why since the code implementation seems simple.
Added logging around env vars and execution flow (or the lack of execution).
After this is deployed and merged in staging, I should be able to read the logs with `ks logs <snack-pod>` and/or `ks attach <snack-pod> -i`
>  [website][debug] add debug code to figure out why .dev transition isn't working in staging

- snackager/src/__integration-tests__/__snapshots__/bundler.test.ts.snap
- snackager/src/__integration-tests__/__snapshots__/lockfiles/@draftbit/ui@40.34.4.lock
- snackager/src/__integration-tests__/__snapshots__/lockfiles/@react-native-community/datetimepicker@3.0.3.lock
- snackager/src/__integration-tests__/__snapshots__/lockfiles/@react-native-community/viewpager@4.2.0.lock
- snackager/src/__integration-tests__/__snapshots__/lockfiles/@react-navigation/stack@5.9.0.lock
- snackager/src/__integration-tests__/__snapshots__/lockfiles/expo-google-app-auth@8.1.3.lock
- snackager/src/__integration-tests__/__snapshots__/lockfiles/expo-linear-gradient@8.2.1.lock
- snackager/src/__integration-tests__/__snapshots__/lockfiles/firestorter@2.0.1.lock
- snackager/src/__integration-tests__/__snapshots__/lockfiles/moti@0.10.0.lock
- snackager/src/__integration-tests__/__snapshots__/lockfiles/react-native-gesture-handler/DrawerLayout@1.6.0.lock
- snackager/src/__integration-tests__/__snapshots__/lockfiles/react-native-gesture-handler@1.6.0.lock
- snackager/src/__integration-tests__/__snapshots__/lockfiles/react-native-reanimated@2.0.0-alpha.6.lock
- snackager/src/__integration-tests__/__snapshots__/lockfiles/react-native-reanimated@2.0.0-rc.3.lock
- snackager/src/__integration-tests__/__snapshots__/lockfiles/react-native-responsive-grid@0.32.4.lock
- snackager/src/__integration-tests__/__snapshots__/lockfiles/react-native-screens/native-stack@2.11.0.lock
- snackager/src/__integration-tests__/__snapshots__/lockfiles/react-native-web/src/modules/normalizeColor@0.14.4.lock
- snackager/src/__integration-tests__/__snapshots__/lockfiles/react-native-webview@10.9.1.lock
- snackager/src/__integration-tests__/__snapshots__/lockfiles/react-navigation@3.13.0.lock
- snackager/src/utils/getBundleInfo.ts
Refreshes the `.lock` files which causes the latest `@babel/runtime` to be used. This causes the tests to closer represent the current reality when bundling. This PR also sorts the reported externals to prevent future test-cases from failing when the generated bundle is slightly different (causing a different import ordering).
- Delete and regenerate `.lock` files so they use the latest `@babel/runtime`
- Sort reported externals
- `yarn test`
- `yarn lint`
- Verified that the externals are unchanged
- Verified that the output size is within expected limits
> [snackager] Update test snapshots

- website/src/expo-dev-migration/index.ts
- website/src/server/index.tsx
After checking the logs and doing a quick search, my new theory is that the redirect code isn't working because we are serving Snack behind an nginx proxy, but we aren't trusting the headers sent from the proxy so we aren't able to find out the original request url. 
- set `app.proxy = true` to enable proxy headers https://koajs.com/#settings
- added new logs to get more info about the request and its context
> [website][debug] set proxy = true and add more log statements for redirect

- website/src/expo-dev-migration/index.ts
- website/src/server/routes.tsx
With the help of logging, I figured out that `app.proxy = true` was the key to getting the redirect code working, so the debug statements I added have now served their purpose and now should be removed.
Removed all `console.log('.DEV Redirect...` statements.
> [website] remove .dev redirect debug statements

- packages/snack-sdk/src/__tests__/sdkversion-test.ts
- packages/snack-sdk/src/index.ts
- packages/snack-sdk/src/sdk.ts
- packages/snack-sdk/src/sdks/index.ts
- packages/snack-sdk/src/sdks/types.ts
- website/src/client/utils/dependencies.tsx
Show warnings for deprecated packages such as `expo-permissions` and `@react-native-community/async-storage`. These warnings help with upgrading Snacks to new latest SDK versions, for instance to SDK 41 and SDK 42.
- Allow defining deprecated packages on a per SDK basis
- Add `getDeprecatedModule` to `snack-sdk`
- Add unit tests for `snack-sdk`
- Show warning in website when a deprecated package is used (see screenshot in #why)
- Verified the warnings pop-up when the deprecated dependencies are added to `package.json`
> [website] Show warnings for deprecated packages

- website/src/client/utils/dependencies.tsx
Make Snack more deliberate and stricter by showing errors when dependencies are missing, instead of just warnings. This ensures that the Snack lists all dependencies, even those that are pre-loaded by the Snack runtime. This contributes to learning how to use Expo correctly and ensures that the project will run when exporting it to a `.zip` file, as well as providing better compatibility with future SDKs.
- Return severity `3` (error) instead of `2` (warning) for annotations regarding preloaded modules
- See screenshots
> [website] Show errors instead of warnings when dependencies are missing

- runtime/src/aliases/index.tsx
- snackager/src/bundler/externals.ts
`@react-native-picker@1.9.11` manually imports [`react-native/Libraries/Components/UnimplementedViews/UnimplementedView`](https://github.com/react-native-picker/picker/blob/master/js/PickerAndroid.js#L11) in some places. This causes Snackager to actually load the unimplemented view from react-native itself. 
Eventually, it will end up with a weird set of dependencies that it thinks it needs to install. Because these aren't available in the registry, this will fail.
> "dependencies":{"React":"*","StyleSheet":"*","View":"*"},"time":"2021-07-01T12:12:38.554Z","v":0,"pkg":{"name":"@react-native-picker/picker","version":"1.9.11"},"msg":"@react-native-picker/picker@1.9.11 installing dependencies: React@*, StyleSheet@*, View@*"}
([see logs](https://github.com/expo/snack/files/6747966/test.txt)) …
> [snackager] Add unimplemented view as external for react native picker

- snackager/k8s/staging/snackager.env
- snackager/src/cache-busting.ts
- snackager/src/utils/__tests__/getCachePrefix.test.ts
Font resources from the `expo-google-fonts` package aren't loaded atm. This is due to mixed resources (HTTP vs HTTPS). This is a test to enable it on staging only.
Updated the k8s staging envvars.
See if this [snack loads properly](https://snack.expo.io/@peterpme/rebellious-orange) on staging.
> [snackager] Use secure cloudfront url for snackager

- website/src/client/components/Publish/PublishManager.tsx
Prevent the save modal from being shown on consecutive saves when you are logged in.
- Do not show save modal after successfully saving when logged in 
- `yarn start`
- Open `http://snack.expo.test`
- Log-in to Snack
- Press "Save" button and witness save modal
- Make some changes to code
- Press "Save" again and witness no save modal anymore
> [website] Hide save modal on consecutive saves

- .github/workflows/runtime-production.yml
- .github/workflows/runtime-staging.yml
- CONTRIBUTING.md
- runtime/README.md
This PR adds automatic deployment of the Snack runtime to the staging and production environment (web-player & native runtime). Previously this needed to be done by hand, which was cumbersome and time consuming.
- Auto deploy to staging upon pushing to main
- Deploy to production by running the `deploy` workflow in `RuntimeProduction`
- Native runtime deploy has been verified
- Web-player deploy is Work in progress, requires S3 credentials config to work
> [ci] Runtime deployment github actions

- snackager/k8s/production/snackager.env
- snackager/src/cache-busting.ts
Follow up to #170 and fixes `@expo-google-fonts/xxx` on production.
- Update cloudfront url to `https`
- Bust cache for `@expo-google-fonts/` as Snackager was re-run on production, causing bundles with the old `http://` url to generated
:eyes:
> [snackager] Fix @expo-google-fonts/xxx not working on production

- .github/workflows/runtime-staging.yml
- .github/workflows/runtime.yml
Run CI runtime workflow for `sdk-*` branches, to allow deployment of the webplayer and native runtime through the `deploy` workflow trigger.
- Run generic `Runtime` workflow on any pull-request (instead of only PRs for main)
- Updated staging workflow to deploy when pushing to `main` or `sdk-*` branches
- No production deployment changes have yet been made in this PR. This will be done after in a new PR after verification of this PR.
- To test auto-deployment to staging will need to be merged. This should cause the webplayer and native runtime (for SDK 41) to be deployed to staging
> [ci] Run staging runtime workflow for sdk branches

- .github/workflows/runtime-production.yml
Follow up to #180 to add deployment to production through "deploy" trigger.
- Add CI action for this branch
After merging, the CI step should run but not deploy. Upon succesful run, the "deploy" trigger should be run to verify deployment of the SDK 41 branch to production
> [ci] Run production runtime workflow for sdk branches

- packages/snack-sdk/CHANGELOG.md
- packages/snack-sdk/src/__tests__/__snapshots__/devsession-test.ts.snap
- packages/snack-sdk/src/defaultConfig.ts
- snackager/src/__integration-tests__/__snapshots__/git.test.ts.snap
- website/src/client/components/App.tsx
- website/src/client/configs/sdk.tsx
Sets the default Expo SDK for snack-sdk to 42.0.0, as well as updates the changelog and makes some type improvements to website. Once completed, the snack-sdk will be published to NPM with these changes.
- Set default SDK in snack-sdk to 42.0.0
- Set default SDK in website to 42.0.0
- Update snack-sdk changelog
- Stricter types for SDK_VERSION constants in website
- Update snackager test snapshots
- snack-sdk `yarn lint && yarn tsc`
- snack-sdk `yarn test`
- website `yarn lint && yarn tsc`
- website `yarn test`
- snackager `yarn test`
> [sdk] Set default SDK to 42 and update changelog

- .github/workflows/runtime-production.yml
- .github/workflows/runtime-staging.yml
- .github/workflows/runtime.yml
This PR updates the runtime CI actions to allow deployment to staging & production from `sdk-*` branches. The changes for this PR were tested on the `sdk-41` branch through #180 and #181. This PR ports them to the main branch so the changes will apply for future sdk versions as well.
- Run generic Runtime workflow on any pull-request (instead of only PRs for `main`)
- Updated staging workflow to deploy when pushing to main or sdk-* branches
- Updated production workflow to deploy when pushing to main or sdk-* branches
- Tested through PR #180 and #181
- Action that confirms the generic `Runtime` action runs on branches other than `main` 
-https://github.com/expo/snack/actions/runs/1014691626
- Action that confirms succesful deployment of Runtime 41 to staging:
- …
> [ci] Run runtime CI workflows for sdk-* branches

- website/src/expo-dev-migration/index.ts
Today is Expo.dev day! We're starting with the main website (expo.dev) and Snack.
> [website] enable snack.expo.dev for everyone

- website/src/client/components/Import/ImportProductionModal.tsx
Fixes imports from production Snacks on the `.dev` domain; and make several improvements to those imports.
- Support `.dev` domain for production imports
- Reset dependencies by default (which is what you want in 99% of the cases)
- Fix appearance of switch
- Verified locally
> [website] Fix imports from production dev domain

- README.md
- docs/embedding-snacks.md
- docs/expo-sdk-upgrade.md
- docs/hosts-ports.md
- docs/snack-sdk-api/README.md
- docs/snack-sdk.md
- docs/url-query-parameters.md
- packages/snack-sdk/README.md
- packages/snack-sdk/src/__mocks__/window.ts
- runtime/src/BarCodeScannerView.native.tsx
- runtime/src/Messaging.web.tsx
- website/README.md
- website/snack-embed.html
- website/src/client/configs/sdk.tsx
Updates the URLs in the documentation to refer to `.dev` when it comes to `expo.io` and `snack.expo.io`. This also adds a small sub-banner which informs the  users of the transition to the `.dev` domain.
- Update `expo.io` -> `expo.dev`
- Update `snack.expo.io` -> `snack.expo.dev`
- Fix several `exp://` urls which were still using `.io` (should have been `exp.host`)
- Add banners to inform users of change to `.dev`
- :eyes:
> [docs] Update to dev domain

- website/src/client/utils/projectNames.tsx
`spontaneous` is misspelt in `emotions` array.
> [website] Fix misspelling of "spontaneous"

- website/package.json
- website/src/client/components/Editor/MonacoEditor.tsx
- website/src/client/components/shared/ResizeDetector.tsx
- yarn.lock
Fixes the initial Monaco editor height. This problem started appearing in Chrome recently and has also been appearing in Firefox. Reported by @EvanBacon 
- Use `react-resize-detector` to detect size changes
- Verified on Chrome 92 locally (mac)
- Verified on Firefox 90 locally (mac)
- Verified on Safari 14.1.2 locally (mac)
- Verified on Edge 92 locally (mac)
> [website] Fix initial editor height

- website/src/client/utils/getWebsiteURL.ts
- website/src/expo-dev-migration/index.ts
The main website and Snack have been migrated for a while now, we so should make this redirect permanent to signal which is the main website for SEO purposes.
Changed response status to 308 and removed reversal code.
> [website] make snack.expo.dev redirect permanent

- website/src/client/components/Editor/MonacoEditor.tsx
- website/src/client/components/shared/ResizeDetector.tsx
Fixes `ResizeObserver loop limit exceeded` error reported in Sentry. Problem was introduced in PR #189.
More information: https://github.com/maslianok/react-resize-detector/issues/45
- Use `debounce` mode for `useResizeDetector`
- Verified resizing works as expected and does not produce any errors locally
- Was unable to reproduce the original error, so not able to verify it fixes the reported problem. As per described [here](https://github.com/maslianok/react-resize-detector/issues/45), assuming this fixes the reported error.
> [website] Fix ResizeObserver loop

- .github/workflows/appetize.yml
We have almost all of the Snack development workflow in Github, except for Appetize. It's a manual step that requires some attention. This should fix that by adding a check & deploy workflow for Appetize.
The workflow contains a couple of steps, with small differences for Android and iOS:
1. Resolve the current version on Appetize (main, embedded, or both queues)
2. Resolve the client version it _should have_ from SDK version
3. Download the client for the specified version
4. Prepare the client for Appetize (iOS only)
5. Upload the client to Appetize (main, embedded, or both queues)
With the inputs, we have a "double failsafe" to prevent undesired deployments. You both have to specify the exact SDK version to use, and you have to confirm with "deploy".
- When omitting both `deploy` and …
> [ci] Add appetize workflow to check and deploy new simulator builds

- .github/workflows/appetize-validation.yml
> Only merge this after #194, it uses the same envvars.
This is a follow-up and related to #194. Instead of deploying Appetize builds, this workflow continuously checks the appetizer versions. We can change the interval, but this would be our trigger (from slack) to start fixing stuff. 
This workflow is doing a couple of things:
- Resolve the configured version from `website/src/client/configs/sdks.tsx`
- Resolve the SDK versions from the versions api
- Check the Appetize version (per platform and per queue)
- Validate the default website version native build with the one on Appetize
There are a few outcomes, here are they:
State | Outcome | Message | Example
--- | --- | --- | ---
Appetize uses same version from default SDK | info | `Appetize (main) build for android (2.21.5) is up to …
> [ci] Add continuous tests for Appetize and website versions

- .github/workflows/snackager-staging.yml
- .github/workflows/website-staging.yml
This prevents PRs from forks to trigger a staging deployment workflow and failing in the process due to missing git secrets.
- Removed `pull_request` trigger from workflows
- Open a PR from a fork 😄
> [ci] Remove pull request triggers on staging deployments

- website/src/client/components/DevicePreview/DevicePreview.tsx
- website/src/client/configs/constants.tsx
this PR update `min-width` according issue for react native docs 
i test the resolution for `iPad Air 4th generation`  horizontally real device width for this device is `674px`,   
after run website example i change `min-width: 600` horizontally and vertically
Before: 
After:
> chore: show embedded preview for horizontal ipad devices

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/questions.yml
- README.md
- docs/url-query-parameters.md
- packages/snack-sdk-legacy/README.md
- packages/snack-sdk-legacy/package.json
- packages/snack-sdk-legacy/src/SnackSession.js
- packages/snack-sdk-legacy/src/__tests__/SnackSession-test.js
- packages/snack-sdk/package.json
- runtime/README.md
- runtime/__internal__/DEPLOYING.md
Forums, blog, emails, and the main website are now on expo.dev, so our code should reflect that.
> update remaining relevant urls to expo.dev

- website/src/client/components/App.tsx
Only programming, or maybe service errors should be logged to Sentry. This removes the explicit sentry logging of dependency errors in the Snack web app.
This removes logging of the `Failed to resolve dependency` and `Invalid dependency` errors that happens because of invalid user input. These are not programming or service errors, but misconfigurations.
```
Failed to resolve dependency 'expo-constant@~11.0.1' (Package 'expo-constant' not found in the registry)
Failed to resolve dependency 'react-native-elements@42.0.0' (Version '42.0.0' for package 'react-native-elements' not found)
Invalid dependency 'expo-constants' (version '~11.0.1-' is not a valid semver)
Invalid dependency '@@blaexpo-constants' (name can only contain URL-friendly characters)
```
In rare cases, it may happen that …
> [website] Do not log dependency errors to Sentry

- website/src/client/components/App.tsx
Fixes an occasional `TypeError: this._broadcastChannel is undefined` error that was detected by Sentry.
https://sentry.io/organizations/expoio/issues/2193424954/?project=191351&referrer=slack
- Improve nullability typing on `_broadcastChannel`
- Optionally call `.close` on unmount
- `yarn lint && yarn tsc`
- Ran website locally and verified that opening the same Snack in a new tab disables auto-save (which is what the BroadcastChannel is used for)
> [website] Fix _broadcastChannel is undefined error

- snackager/src/cache-busting.ts
- snackager/src/utils/packageBundle.ts
All of the `moti` / `@motify/` libraries require the reanimated plugin.
- Added the org to the bundler
- Added cache busting to rebuild the libraries
- See if staging works with [this snack](https://snack.expo.dev/@beatgig/courageous-peach)
> [snackager] Add motify org to forced reanimated plugin bundling

- website/src/server/index.tsx
Right now, having no Sentry credentials available crashes the server. This should allow Sentry to be non-initialized.
Check if Sentry DSN is defined before init the library.
Deploy to staging and see if it works.
> [website] Allow Sentry to init on server when undefined

- packages/snack-sdk/CHANGELOG.md
- packages/snack-sdk/src/Session.ts
- packages/snack-sdk/src/__tests__/connections-test.ts
Fixes the `connectedClients` dictionary which sometimes contained entries without a device id, name, platform and transport field.
This happened because in some cases the error and log messages from the connected client were received before the presence was advertised over PubNub. This in turn caused errors on the Snack website when for instance loading a Snack which contained an error, and using the Expo Go client to connect to it.
Fixes #208
- Ignore protocol messages from connected-clients if received before the `connect` presence event (and also after a client advertises that it left)
- Add unit test to verify that no connected clients are created upon receiving error/log messages
- New unit test passes
- Verified that the new unit test failed without the modification
> [snack-sdk] Fix connected-clients not having id, name and platform

- website/src/client/components/Markdown/markdown.css
Currently links in Markdown preview are rendered using default blue color.
Let's switch this to Expo purple to make those fit the website palette a bit better. 🙂 
Set color of links directly in `markdown.css` overwrites.
The change has been tested running Snack website locally.
> [website] Use purple for links in Markdown preview

- website/src/client/components/Search/SearchBar.tsx
- website/src/client/components/Search/algolia.css
I have spotted that Algolia search results layout looks a bit off (too much spacing). This might be the result of Snack CSS overwrites, but AFAIK a few weeks ago it was still looking fine. 🤷‍♂️ 
This PR fixes the Algolia search results UI, switches to violet as highlight color and also tweaks few colors in the dark mode.
I have tested the changes running the Snack website locally.
> [website] fix Algolia search results UI

- website/src/client/components/shared/Modal.tsx
Currently, when user overselect the input or other content inside Modal, it automatically closes, which could be a bit annoying.
This is because the click started inside the modal ends outside of it, and click ends on the Modal overlay.
To prevent this behaviour I have swapped the `onClick` listener to `onMouseDown` for the modal overlay component. 
The change has been tested running the Snack website locally.
> [website] do not dismiss modal on content overselect

- docs/snack-sdk-api/README.md
- docs/snack-sdk-api/classes/snack.md
- packages/snack-sdk/src/Session.ts
- packages/snack-sdk/src/types.ts
- snackager/src/__integration-tests__/__snapshots__/bundler.test.ts.snap
- website/src/client/components/App.tsx
- website/src/client/types.tsx
- website/src/client/utils/Analytics.tsx
We'd like to anonymize events by removing mentions of account name or username to hit GDPR specs. This converts snack tracking id to uuid.
needs to be landed after this [PR](https://github.com/expo/universe/pull/8727) for `www` to have `/snack/save` return `uuid`.
Grabbed the UUID from the saved snack response and populated the analytics id with it.
Ran some test events locally to confirm the id had updated.
> [snack-sdk][website][snackager][docs] track events by uuid

- website/src/client/components/EditorView.tsx
- website/src/client/components/Preferences/PreferencesProvider.tsx
Currently, often first thing done when I open a new Snack is to change the theme to dark mode. 😅 
Since the editor preferences are non-crucial or sensitive data in any way we can use the browser local storage to store them to improve the users UX.
This PR adds store and load code for the editor theme and mode.
I have placed this on top of all overrides for it has the less priority and will be overwritten by, for example, theme provided in query string.
Also to improve the readability a bit I have extracted the editor mode possible values to the separate type.
The changes have been tested by running the website code on localhost.
> No preferences in LS => Set/toggle preferences => Reload website
> [website] store editor theme and mode in local storage

- website/src/client/components/EditorView.tsx
- website/src/client/components/Preferences/withThemeName.tsx
Without this, the syntax highlighting might be wrong when for null theme values.
- Sanitized the theme name in the theme context provider
- Converts `ThemeName | null | undefined` to `ThemeName` (defaults to `light`).
- See if staging works
> [website] Sanitize theme name to light or dark only

- .github/workflows/snackager-production.yml
- .github/workflows/snackager-staging.yml
The Snackager production and staging workflows were failing because tsc could not find snack-content's types. Perhaps we could use skipLibChecks in tsconfig.json but I addressed this by building the snack-content and snack-sdk packages before running tsc in snackager.
In a completely clean repo (`git clean -dfx`) I ran the same steps as CI:
```
cd snackager
yarn install --ignore-scripts --frozen-lockfile
yarn tsc --noEmit
```
Verified I got type lookup errors. Then built snack-content and snack-sdk and ran tsc successfully.
> Fix snackager build

- packages/snack-content/src/sdks/features.ts
- packages/snack-content/src/sdks/types.ts
www needs to check for some of these features. Adding back all of them since the goal of splitting out snack-content was not to change the public API.
Just added back all the features
Ran unit tests in snack-content
> [snack-content] Add back detection for all features

- .github/workflows/runtime-production.yml
- .github/workflows/runtime-staging.yml
Always nice to keep this updated.
Bumped up the workflow version
See if CI works.
> [runtime] Bump expo github actions to v7

- website/src/client/components/UserMenu.tsx
CC: @jonsamp 
Currently, when users logs in, in the menu appear link to "My Snacks", which currently redirects user to the public profile including Snacks tab. This might cause some confusion for the users.
Let's switch the URL to the Snack list located in Dashboard. User need to be logged in, to see the link in the first place, so switching to the protected view should not results in any issues.
The change has been tested by running the Snack website locally.
> [website] link to Dashboard Snacks list instead of public one

- website/src/server/components/RudderStackDocumentComponent.tsx
Rudderstack is [deprecating](https://rudderstack.com/docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/) v1 in favor of v1.1 (it is also 2/3 smaller in size)
Bumped the version # in the initializer snippet.
Plan to run in staging to confirm events make it to the backend
> [website] bump rudder sdk

- website/Dockerfile
- website/skaffold.yaml
- Fixes our pipeline again
- Probably should upgrade this to node 16 too
- Upgraded Dockerfile for website
- Upgraded Skaffold node versions
- CI is left intact, as it uses the latest 12 already
- See if CI staging deployment passes
> [website] Bump node to 12.22.11 and use node alpine image

- package.json
Running the project via `yarn start` does not work with the current version of node, nor does it work with 12.22.11. There don't seem to be any issues with upgrading directly to the latest stable version of Node 16.
Bump the volta node version in package.json.
Run `yarn start` in root of the repo.
> Bump node to 16.14.2

- .github/workflows/runtime-production.yml
- .github/workflows/runtime-staging.yml
- .github/workflows/runtime.yml
The runtime still inherits some basic eslint tools from the root of the monorepo. That's why it also should install those dependecies.
- Added "install monorepo dependencies"
- Added names for each steps to identify what they are doing
CI should pass after merging #271
> [runtime] Fix linting in CI for runtime

- runtime/package.json
- runtime/patches/react-native-reanimated+2.3.3.patch
- runtime/src/Modules.tsx
- runtime/yarn.lock
Instead of letting yarn install two separate instances of a package, we copy the plugin before applying a patch to it. That way, we can use a version in the snack runtime, and one in the snack code itself.
We might want to look for alternatives to this issue though.
- Replaced "install this package twice" with:
- Copy `plugin.js` to `plugin-standalone.js`
- Apply the patch to `plugin-standalone.js`
See if staging works
> [runtime] Replace non-deterministic yarn behavior with two same packages

- .github/workflows/runtime-production.yml
- .github/workflows/website-production.yml
- .github/workflows/website-staging.yml
- .github/workflows/website.yml
- website/package.json
- website/skaffold.yaml
- website/src/client/components/Import/ImportFilesManager.tsx
- website/tsconfig.json
- yarn.lock
We want all of snack to be using Node 16 over 12
* [website] Update CI to use Node 16
* [website] Bump to Node 16.14.2
* [website] Remove TS reference to snack-sdk and snack-content
* [website] Update skaffold to reflect node 16.14.2
TBD
> Update website to Node 16

- website/Dockerfile
Unblocks us from deploying the website. Will test staging first.
Instead of selectively parsing/building packages, we just copy the whole repo and build it for production. In the last step, only the built files are copied into the deployed production image.
- Deploy to staging and see if the website is fully functional
> [website] Rework dockerfile to assume monorepo structure

- packages/snack-content/package.json
- packages/snack-content/src/defaults.ts
- packages/snack-sdk/package.json
- packages/snack-sdk/src/__tests__/__snapshots__/dependencies-test.ts.snap
- packages/snack-sdk/src/__tests__/__snapshots__/devsession-test.ts.snap
- packages/snack-sdk/src/__tests__/sdkversion-test.ts
Rolling out SDK 44 support fully.
Minor updated `snack-sdk` and `snack-content`.
- Tested on both staging and production (in that order ofc 😄)
> [packages] Prepare snack-sdk and snack-content for SDK 44

- .github/workflows/snackager-production.yml
- .github/workflows/snackager-staging.yml
- .github/workflows/website-production.yml
- .github/workflows/website-staging.yml
We are moving all our services to a new kubernetes cluster.
For both snackager and the website, on both the staging and production workflows, after successfully rolling out any changes to `exp-central`, the workflow runs `gcloud container clusters get-credentials --region us-central general-central`, which both creates and activates a kubectl config context that works for the cluster named `general-central`.  Then it re-runs the `skaffold deploy` command, rolling out the same changes to the new cluster.
On my own machine, i was able to run `skaffold run` for snackager and the website on staging and production of the new cluster, so I'm confident that the deployments can stabilize.
I'll make changes outside of this PR to migrate traffic to the services running in the new cluster.  And once …
> [CI] Add rollouts to general-central

- snackager/src/bundler/externals.ts
Currently, bundling of `react-native-maps@0.29.4` fails with the error:
```
Failed to resolve dependency 'react-native-maps@0.29.4' (Module not found: Error: Package path ./unstable-native-dependencies is not exported from package /tmp/snackager/snackager/buildStatus/1/react-native-maps@0.29.4-ios,android,web/package/node_modules/react-dom (see exports field in /tmp/snackager/snackager/buildStatus/1/react-native-maps@0.29.4-ios,android,web/package/node_modules/react-dom/package.json)
Retry
Module not found: Error: Package path ./unstable-native-dependencies is not exported from package /tmp/snackager/snackager/buildStatus/1/react-native-maps@0.29.4-ios,android,web/package/node_modules/react-dom (see exports field in /tmp/snackager/snackager/buildStatus/1/react-native-maps@0.29.4-ios,androi …
```
> [snackager] Add explicit RN web external for react native maps

- runtime/src/aliases/index.web.tsx
Without this, it can't resolve the external added in #283 
- Added external in runtime web aliases
- See if staging works.
> [runtime] Add missing web external for react-native-maps

- .github/actions/setup-runtime/action.yml
- .github/workflows/runtime.yml
- .github/workflows/snackager.yml
Just like Snackager's workflow #285, unify the runtime.
- Unified with environments and additional manual deploy options.
- See if CI successfully deploys
> [runtime] Unify github workflows like snackager

- runtime/src/aliases/index.tsx
- snackager/src/bundler/externals.ts
Stripe uses this one, so we need to mark it as external.
Would be better if we can use the package-spec instead. e.g.
- `react-native/*` → external because of `react-native`
- Check if `@stripe/stripe-react-native` builds with Snackager
> [There is an ongoing issue with the files pointing to a non-existing `package.json`. Once this is resolved, we can test this](https://github.com/stripe/stripe-react-native/pull/924).
> [snackager] Add missing text input external for Stripe

- website/package.json
- yarn.lock
Fixes #291
We lazy-load prettier in the website whenever it's requested ([here](https://github.com/expo/snack/blob/main/website/src/client/utils/prettierCode.tsx#L12)), but we don't explicitly mention prettier as dependency in website. This will not install prettier as dependency in the production environment.
Added prettier dependency to website
Deploy to staging, see if it works.
> [website] Add prettier to dependencies to lazy load in production

- snackager/src/utils/__tests__/resolveDependencies.test.ts
- snackager/src/utils/resolveDependencies.ts
Reanimated has listed `@babel/core` as peer dependency, and is therefore triggering a "Package requires babel, do you want to install it?". This package specifically should never be added manually. We use a custom babel pipeline in the runtime to transpile user-input on the fly, and it would break with adding babel inside babel.
Added _hidden peer dependencies_, next to _ignored dependencies_ when resolving package dependencies.
See added unit test + CI
> [snackager] Hide babel peer dependencies from dependency list

- packages/snack-content/src/defaults.ts
- packages/snack-sdk/src/__tests__/__snapshots__/dependencies-test.ts.snap
- packages/snack-sdk/src/__tests__/__snapshots__/devsession-test.ts.snap
- snackager/src/__integration-tests__/__snapshots__/git.test.ts.snap
- snackager/src/utils/__tests__/resolveDependencies.test.ts
- snackager/src/utils/resolveDependencies.ts
- website/package.json
- website/src/client/configs/sdk.tsx
Getting ready to publish to production, but while the #292 issue is still ongoing avoid making it the default.
Set default back to 44, and centralized the switch through `snack-content` package
See if CI succeeds
> [website] Set default back to sdk 44 and centralize switch

- packages/snack-content/tsconfig.json
- packages/snack-proxies/tsconfig.json
- packages/snack-sdk/tsconfig.json
- packages/snack-term/tsconfig.json
- runtime/tsconfig.json
- snackager/tsconfig.json
- website/tsconfig.json
During development this could easily happen, e.g. when testing parts of the code. By letting the code be built, even though it contains dead code, it should help improve DX. We still test for unused code through eslint.
Removed two typescript rules:
- `noUnusedLocals`
- `noUnusedParameters`
See if CI still works.
> Use eslint to rely on unused code detection

- website/src/client/components/Router.tsx
- website/src/server/index.tsx
- website/src/server/routes.tsx
- website/webpack.config.js
Fixes [ENG-5064](https://linear.app/expo/issue/ENG-5064/fix-caching-headers-for-snacks-static-assets-and-404s)
Our CDN cached a 404 response for some chunks of assets, causing Snack to break until the CDN was flushed. This should help tell the CDN to not-cache 404 responses.
Snack's website is a kind of custom-built, a legacy from how it was created years ago. So the implementation is not ideal, but here is how it works:
- Koa tries to serve static files first. If that doesn't exist, it continues through the other middlewares.
- When no static files are found, it server-side renders the **src/client/components/Router.tsx** 
- If that client router is being rendered server-side, pass the server context.
- Whenever the client router needs to respond with a not-found page, set the right …
> [website] Set status code for not found responses to avoid CDN caching

- website/package.json
- yarn.lock
Right now, prettier throws an internal error caused by some Terser processing issues.
Pinned prettier to the last known working version (the [one supporting `jsxBracketSameLine`](https://prettier.io/blog/2021/09/09/2.4.0.html#replace-jsxbracketsameline-option-with-bracketsameline-option-11006httpsgithubcomprettierprettierpull11006-by-kurtztechhttpsgithubcomkurtztech))
Run from docker, or run on staging. Click the prettier button.
> [website] Pin prettier to last known working version

- .github/workflows/appetize-validation.yml
Because we reuse the default SDK version from `snack-content`, that needs to be available in this workflow too.
Because we want to check the websites SDK configuration, I reused `actions/setup-website` to set things up. That should always include the right files and builds to transpile and load the **website/src/client/configs/sdk.ts** file.
See if "Appetize Validation" workflow passes.
> [ci] Fix the Appetize validation workflow

- website/README.md
- website/src/client/components/App.tsx
Snack URLs already support the query param `platform`; however, when sharing the URL for a Snack, it does not reflect the `platform` in the URL. The desired UX here should just be copying and pasting the URL in the browser.
Use `window.history.pushState()` to update the current url based on the platform selected
1. Run `yarn && yarn build` from the root
2. Run `yarn start` from the root
3. Within the Device Preview window, toggle the device ("My Device", "iOS", "Android", "Web") and observe the URL change in the browser search bar.
> [website] Update URL on Device Preview Toggle

- packages/snack-sdk/src/Session.ts
- packages/snack-sdk/src/WantedVersions.ts
- packages/snack-sdk/src/__mocks__/www.ts
Fixes [ENG-5177](https://linear.app/expo/issue/ENG-5177/implement-native-module-api-endpoint)
Adds the versioned modules endpoint next to `bundledNativeModules.json` in the SDK.
See SDK
Will go to staging too
> [snack-sdk] Add versioned endpoints for modules

- packages/snack-sdk/src/Session.ts
- packages/snack-sdk/src/WantedVersions.ts
- packages/snack-sdk/src/__mocks__/www.ts
- website/src/client/components/Editor/MonacoEditor.tsx
- website/src/client/components/Editor/types/README.md
- website/src/client/components/Editor/types/vendored.ts
- website/src/client/workers/typings.worker.tsx
This adds two main things to the website's editor:
1. Warning when types couldn't be loaded + steps to fix it.
2. Vendored types, where `@shopify/react-native-skia/dist/web` is the vendored type.
- Updated typescript worker to add `errorMessage` and skip caching in cases of failures
- Added vendored types
Onwards to staging, and try to load [https://staging.snack.expo.dev/@bycedrictest/universal-skia-demo](https://staging.snack.expo.dev/@bycedrictest/universal-skia-demo)
> [website] Add type failure warning and vendored types

- packages/snack-babel-standalone/package.json
- packages/snack-babel-standalone/src/runtime.ts
- packages/snack-babel-standalone/yarn.lock
- packages/snack-eslint-standalone/package.json
- packages/snack-eslint-standalone/src/config.ts
- runtime/package.json
- runtime/src/Modules.tsx
- runtime/src/aliases/common.tsx
- runtime/yarn.lock
- website/package.json
- website/src/client/components/Editor/MonacoEditor.tsx
- website/src/client/components/Editor/types/vendored.ts
- website/src/client/configs/defaults.tsx
- website/src/client/workers/typings.worker.tsx
- yarn.lock
Enables the automatic JSX runtime, which means not having to do `import React from 'react';` in every file.
- Added plugin to `snack-babel-standalone`
- Disabled rule `react-jsx-in-scope` in `snack-eslint-standalone`
- Updated `runtime` with the new plugin
- Updated `website` for the new eslint default config
Going to staging!
> Enable automatic jsx runtime

- packages/snack-babel-standalone/package.json
- packages/snack-babel-standalone/src/runtime.ts
- packages/snack-babel-standalone/yarn.lock
- packages/snack-eslint-standalone/package.json
- packages/snack-eslint-standalone/src/config.ts
- runtime/package.json
- runtime/src/Modules.tsx
- runtime/src/NativeModules/getDeviceIdAsync.web.tsx
- runtime/src/aliases/common.tsx
- runtime/yarn.lock
- website/package.json
- website/src/client/components/Editor/MonacoEditor.tsx
- website/src/client/components/Editor/types/vendored.ts
- website/src/client/configs/defaults.tsx
- website/src/client/workers/typings.worker.tsx
- yarn.lock
When running incognito mode, the runtime doesn't load due to device id using unprotected local storage.
- Added a fallback singleton to use
- Open Chrome
- Go incognito
- See if the runtime actually loads.
> [runtime] Fix device id for incognito mode

- packages/snack-babel-standalone/package.json
- packages/snack-babel-standalone/src/eslint.ts
- packages/snack-eslint-standalone/README.md
- packages/snack-eslint-standalone/package.json
- packages/snack-eslint-standalone/src/config.ts
- packages/snack-eslint-standalone/src/eslint.ts
- packages/snack-eslint-standalone/types/eslint.d.ts
- packages/snack-eslint-standalone/yarn.lock
- website/package.json
- website/src/client/utils/lintCode.tsx
- website/src/client/utils/lintFile.tsx
- yarn.lock
ESLint provided a false-positive on the following code:
```ts
async process<Input, Output>(inputData);
```
- Added custom config merging `getLinterConfig` method in eslint standalone
- Added filename to eslint linting code in website, to enable babel features
Test staging with this snack: https://snack.expo.dev/@ansonsyfang/anime-reality
> [website] Fix double generic typescript method eslint errors

- packages/snack-eslint-standalone/babel.config.js
- packages/snack-eslint-standalone/jest.config.js
- packages/snack-eslint-standalone/package.json
- packages/snack-eslint-standalone/patches/eslint+8.20.0.patch
- packages/snack-eslint-standalone/src/__tests__/config.test.ts
- packages/snack-eslint-standalone/src/__tests__/eslint.test.ts
- packages/snack-eslint-standalone/src/__tests__/fixtures/snack-app.js
- packages/snack-eslint-standalone/src/config.ts
- packages/snack-eslint-standalone/src/eslint.ts
- packages/snack-eslint-standalone/webpack.config.js
- packages/snack-eslint-standalone/yarn.lock
- website/package.json
- yarn.lock
Fixes #339
ESLint is having issues with their `undef` rule, on typescript structures such as:
```ts
export type Something = string;
export enum State {
IDLE = 'idle',
PENDING = 'pending',
RESOLVED = 'resolved',
REJECTED = 'rejected',
}
```
- Added Jest setup for `snack-eslint-standalone`
- Added tests for these cases in `snack-eslint-standalone`
- Replaced default eslint rules with `@babel` rules.
See tests
> [snack-eslint-standalone] Fix faulty undef for typescript files

- CONTRIBUTING.md
Fixes #350 
To update the contribution docs (`CONTRIBUTING.md`) to include `yarn build` step.
Follow contributing guide (https://github.com/expo/snack/CONTRIBUTING.md) to set up Snack for local development. Ensure you are able to visit expo at http://localhost:3011 after installation.
> [docs] Update contributing guide

- runtime/src/aliases/index.tsx
- snackager/src/bundler/externals.ts
This is being used in https://github.com/react-native-webview/react-native-webview/blob/76826691dfa1aac44e280575e98701bbef75c28f/src/WebView.android.tsx#L12.
- Added external to Snackager
- Added alias to runtime
It would be great if Snackager can just return the externals we need, and just before loading the module, we could automatically set those aliases.
Staging
> Add missing external for react-native-webview

- runtime/src/Modules.tsx
See: https://twitter.com/jamonholmgren/status/1561798978269618177
Added a global `__DEV__` to the Snack Runtime.
Try logging `console.log('DEV', __DEV__)` in the App's render.
> [runtime] Set __DEV__ explicitly to false

- website/src/client/components/App.tsx
We have dropped support for SDK 39 a while ago.
Remove the legacy web preview workaround.
The web preview was loading correctly when running Snack stack locally.
> [website] remove legacy workaround for SDK 39 and below

- website/src/server/EmbeddedSnackScript.tsx
`data-snack-files` allows specifying specific filenames for code, instead of `data-snack-code` which is placed as `App.js`, or `data-snack-id` which points to a saved Snack. `data-snack-files` replaces `data-snack-code` if present, but an element with only the former will not be initialized.
This adds `data-snack-files` to the list of searched for elements, to catch embedded snacks not using `data-snack-code` (e.g. to embed TypeScript instead of JavaScript).
Before the change, using data-snack-files in the react-native website would lead to blank snack examples when switching through tabs. Snacks show correctly after monkey-patching in the new function.
> Fix initializing embedded snacks using `data-snack-files`

- .github/actions/setup-google-cloud/action.yml
GHA made a breaking change by not-adding python v2.7 for Ubuntu 22.04 in `actions/setup-python` (https://github.com/actions/setup-python/issues/543). Because we use v2.7 in our workflows, this now fails.
- Pulled out python v2.7 from the gcloud workflow
See if we can deploy to staging.
> refactor: remove custom python version from gcloud setup

- bin/prune-gcr
See: https://github.com/expo/snack/pull/363
Thanks to our lovely ppl working on GHA introducing a breaking change of not supporting python v2.7 anymore...
Added missing parenthesis to all print statements
Check if we can deploy staging.
> refactor: migrate prune gcr script to python 3

- .github/actions/setup-secrets/action.yml
- .github/workflows/runtime.yml
- .github/workflows/snackager-bundle.yml
- .github/workflows/snackager.yml
- .github/workflows/website.yml
This should help not-failing CI when external contributors are opening PRs.
Moved unlock to composite action, and skip it when the key isn't available (e.g. in forks).
Check if CI works.
> chore: skip git crypt unlock when running in forks

- website/src/client/components/Editor/SimpleEditor.tsx
Syntax highlighting for embedded snacks using tsx is poor in comparison to jsx. The issue does not show in the full website.
**jsx**
**tsx**
I haven't tried to test this, but looking through to find where syntax highlighting was happening, I noticed that `SimpleEditor` was setting a language of 'typescript' for tsx files, instead of 'tsx' https://github.com/PrismJS/prism/blob/master/components/prism-tsx.js This seems suspiciously like the issue being seen, so this change makes it so that tsx files in SimpleEditor set the correct language.
I am not familiar with this code, so please let me know if this isn't the right place for embedded snacks, or if there is a way to easily test.
> Fix syntax highlighting for embedded tsx files

- snackager/Dockerfile
- snackager/skaffold.yaml
- snackager/src/app.ts
This seems to be missing from the current image, causing `https://<snackager>/version` to return `development` in production.
- Added `APP_VERSION` to the final image, based on skaffold build argument
- `https://<snackager>/version` should not return `development` as version
> fix(snackager): explicitly add the app version to the final image

- packages/snack-sdk/src/Session.ts
- packages/snack-sdk/src/__tests__/webplayer-test.ts
- packages/snack-sdk/src/types.ts
- website/src/client/components/App.tsx
local webplayer is hanging in connecting state.
the `Snack` sdk class only supports fixed webplayer url in construction. after switching to local webplayer, the transport still send message to old origin (our cloud `SNACK_WEBPLAYER_URL`). that's why website cannot connect to runtime correctly.
this pr adds a `setWebPlayerURL` function to change the webplayer URL in snack-sdk. once we changed the url, we should also re-create a new webplayer transport.
```
PASS  src/__tests__/webplayer-test.ts
webpreview
✓ updates a webplayer url (1 ms)
```
1. `yarn start` in workspace root
2. `NODE_OPTIONS='--openssl-legacy-provider' npx expo start -w` in runtime
3. open http://snack.expo.test and switch sdk to localhost
> [snack-sdk][website] Fix local webplayer hanging in connecting state

- snackager/k8s/base/service.yaml
- snackager/k8s/production/kustomization.yaml
- snackager/k8s/production/service-backend.yaml
- snackager/k8s/staging/kustomization.yaml
- snackager/k8s/staging/service-backend.yaml
- snackager/src/app.ts
- website/deploy/base/deployment.yaml
- website/deploy/base/service.yaml
- website/deploy/production/kustomization.yaml
- website/deploy/production/service-backend.yaml
- website/deploy/staging/kustomization.yaml
- website/deploy/staging/service-backend.yaml
- website/package.json
- website/src/server/index.tsx
- yarn.lock
There's some things that are beneficial or required before I can set up our new front end servers to handle requests to the snack website and snackager.
- [website] Don't use stoppable
- Set keep-alive timeout to 10m20s
- Connect k8s services to Google Backend Services
- [website] Fail readiness probe when shutting down
> Prepare for Google front-end servers

- .github/workflows/website.yml
- website/deploy/production/service-backend.yaml
- website/deploy/staging/service-backend.yaml
This fixes deployment.
This was surprisingly difficult to find; `skaffold deploy` is silently exiting with status 1 because `kustomize build` exits with status 1, but skaffold doesnt expose the error message which kustomize prints.  Maybe newer versions of skaffold handle this better.
I ran `kustomize build` on the staging and production configuration.  (CI could detect mistakes like this in future PRs by running that command).
> [website] Correct service backend patches

- packages/snack-content/src/defaults.ts
- packages/snack-sdk/package.json
- packages/snack-sdk/src/__tests__/__snapshots__/dependencies-test.ts.snap
- packages/snack-sdk/src/__tests__/__snapshots__/devsession-test.ts.snap
- snackager/src/__integration-tests__/__snapshots__/git.test.ts.snap
We are preparing to add SDK 48, this wasn't done yet.
Updated the packages and config
> chore: use expo sdk 47 by default

- packages/snack-sdk/src/transports/ConnectionMetricsEmitter.ts
- packages/snack-sdk/src/transports/TransportImplSocketIO.ts
- packages/snack-sdk/src/transports/index.ts
- website/src/client/utils/snackTransports.tsx
- website/src/client/workers/SnackTransport.worker.tsx
close ENG-7102
#376
#377
#378 
#379
👉 #380 
#381
- [website] Add two snackpub metrics for connection quality analytics
- `TRANSPORT_CONNECTION_SUCCEEDED` with elapsed time ms and attempt times
- `TRANSPORT_CONNECTION_FAILED` with elapsed time ms and attempt times
- we don't have analytics for runtime, so runtime is not covered by this metrics
snackpub integration test
> [snack-sdk][website] add snackpub metrics

- packages/snack-sdk/src/transports/TransportImplSocketIO.ts
- runtime/src/transports/RuntimeTransportImplSocketIO.ts
- snackpub/src/RateLimiter.ts
- snackpub/src/RedisAdapter.ts
- snackpub/src/index.ts
- snackpub/src/types.ts
close ENG-7105
#376
#377
#378 
#379
#380 
👉 #381
add rate limiter:
- 30 connections per IP per hour
- 600 messages per socket.id per second and 6000 messages per socket.id per minute
- 30 channels per socket.id per minute
snackpub manual test
> [snack-sdk][website][runtime] add rate limiter

- .github/workflows/snackpub.yml
- snackpub/jest.config.js
- snackpub/package.json
- snackpub/src/NetworkUtils.ts
- snackpub/src/RateLimiter.ts
- snackpub/src/__tests__/NetworkUtils-test.ts
- snackpub/src/index.ts
follow up https://github.com/expo/snack/pull/381#discussion_r1080836193
- read the address from the `X-Forwarded-For` first then the socket remote address
- because cloud run doesn't log the remote address as http access log, this pr also adds remote address to log.
- add `getRemoteAddress` unit test
- ci passed
> [snackpub] read correct remote address behind load balancer

- snackpub/src/index.ts
remove the `fetchSockets` code which getting timeout occasionally.
```
Error: timeout reached while waiting for fetchSockets response at Timeout._onTimeout (/app/node_modules/@socket.io/redis-adapter/dist/index.js:559:28) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
```
close ENG-7773
(this should be the last one pr for us to test snackpub on production. there's still a server readiness check task and i'll do it after production testing).
originally i used `fetchSockets` to get the socket's custom data - `deviceId` when `join-room`/`leave-room`.  the `fetchSockets` is not efficient and requires more expensive work for querying data from redis adapter. it turns out that we don't have to send the `joinChannel`/`leaveChannel` from …
> [snackpub] better join/leave channel

- snackpub/src/HttpEndpoints.ts
- snackpub/src/RedisAdapter.ts
- snackpub/src/__tests__/HttpEndpoints-test.ts
- snackpub/src/index.ts
- snackpub/src/types.ts
follow up https://github.com/expo/snack/pull/377#pullrequestreview-1247080929
close ENG-7693
- add `/status/live` support which always returns 200 from snackpub
- add `/status/ready` support which returns 200 when all redis clients are ready, otherwise returns 503.
```
PASS  src/__tests__/HttpEndpoints-test.ts
ReadOnlyRequestsHandler
✓ should return http 405 for any DELETE/POST/PUT requests (1 ms)
✓ should allow GET/OPTIONS requests
LivenessRequestHandler
✓ should return http 200 for `/status/live` requests
ReadinessRequestHandler
✓ should return http 200 for `/status/ready` requests when not using redis adapters
✓ should return http 200 for `/status/ready` requests when redis clients are all ready
✓ should return http 503 for `/status/ready` requests if any redis client unavailable
``` …
> [snackpub] support readiness http requests

- packages/snack-sdk/src/transports/__mocks__/index.ts
- packages/snack-sdk/src/transports/index.ts
- runtime/src/Messaging.tsx
- website/src/client/components/App.tsx
- website/src/client/utils/snackTransports.tsx
- website/src/client/workers/SnackTransport.worker.tsx
- website/src/server/utils/getSplitTests.tsx
next step to rollout snackpub on production - having a snackpub only transport without traffic mirroring for pubnub
add `testTransport=snackpubOnly` support
- ci passed
- test `http://snack.expo.test/?testTransport=snackpubOnly` and check no pubnub xhr requests.
> [sdk][runtime][website] Support snackOnly transport

- snackpub/src/index.ts
fix server crash from the staging/production log
```
node:assert:399
throw err;
^
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
(0, assert_1.default)(sender)
at Socket.<anonymous> (/app/snackpub/build/index.js:86:34)
at Socket.emit (node:events:526:28)
at Socket.emitReserved (/app/node_modules/socket.io/dist/typed-events.js:56:22)
at Socket._onclose (/app/node_modules/socket.io/dist/socket.js:467:14)
at Client.onclose (/app/node_modules/socket.io/dist/client.js:246:20)
at Socket.emit (node:events:538:35)
at Socket.onClose (/app/node_modules/engine.io/build/socket.js:304:18)
at Object.onceWrapper (node:events:645:28)
at WebSocket.emit (node:events:526:28)
at WebSocket.onClose (/app/node_modules/engine.io/build/transport.js:110:14) {
generatedMessage: true, …
```
> [snackpub] Fix disconnecting server assertion error

- packages/snack-sdk/src/Session.ts
- packages/snack-sdk/src/__tests__/snack-sdk.ts
- packages/snack-sdk/src/defaultConfig.ts
originally, the snackpub server url is passed from website. to serve snack for third party partners, we should have default snackpub server url inside snack-sdk.
add default `snackpubURL` to snack-sdk
ci passed
> [sdk] add default snackpubURL

- packages/snack-sdk/src/Session.ts
- packages/snack-sdk/src/__tests__/snack-sdk.ts
- packages/snack-sdk/src/defaultConfig.ts
- packages/snack-sdk/src/transports/__mocks__/index.ts
- packages/snack-sdk/src/transports/index.ts
- runtime/src/Messaging.tsx
- website/src/client/components/App.tsx
- website/src/client/types.tsx
- website/src/client/utils/snackTransports.tsx
- website/src/client/workers/SnackTransport.worker.tsx
- website/src/server/utils/getSplitTests.tsx
to help third party partners to migrate snackpub without further code changes, we should replace the original `createTransport()` underlying transport from pubnub to snackpub. 
- replace the original `createTransport()` underlying transport from pubnub to snackpub. since it changes the semantics of the default transport, we should align the changes across snack-sdk and snack-runtime.
- [sdk] keeps only `createTransport()` and `createTrafficMirroringTransport()`. i.e. removes the `createSnackPubTransport()` and `createSnackPubOnlyTransport()`
- remove the testTransport a/b testing. now it's all snackpub by default. we could still use `?testTransport` to override transport. it's just not served from http cookie specified from server.
- the `testTransport` is now accepting `snackpub` or …
> [sdk][runtime][website] use snackpub as default transport

- .github/workflows/website.yml
- website/src/client/configs/defaults.tsx
Currently:
- The `Readme.md` file doesn't mention Discord community
- The docs link (even though redirect works) is outdated
- The link to forums does not work: https://forums.expo.io/c/snack
This PR:
- Adds a link to the Discord community
- Updates the docs link
- Fixes how we use "Expo CLI" as a term (we're now using `expo-cli` for deprecated global CLI)
- Fixes the broken link to forums with https://forums.expo.dev/c/expo-dev-tools/61 as we guide developers to use dev tools section on forums now for any issues related to snack
N/A
> [website] Update Readme.md file defaults

- packages/snack-sdk/CHANGELOG.md
- packages/snack-sdk/src/transports/TransportImplBase.ts
- packages/snack-sdk/src/transports/TransportImplPubNub.ts
- packages/snack-sdk/src/transports/TransportImplSocketIO.ts
We have 32768 limit for code diff for PubNub transport and the `32768` limit is hardcoded in different places. I didn't implement similar logic in socketio transport, so it will actually transfer `'X'.repeat(32768)` as the file content in transport. 
- implement 32768 limit on TransportImplSocketIO
- centralize the 32768 limit
- working example: https://staging-snack.expo.dev/@kudochien/long-snack (since i've deployed the pr to staging)
- not working example: https://snack.expo.dev/@kudochien/long-snack
> [sdk] fix code diff limit for snackpub transport

- .github/workflows/runtime.yml
We need to temporarily ignore web deployments. This allows us to do that.
Updated workflow with additional input.
See actions.
> chore(runtime): allow single platform runtime deployments

- website/src/client/configs/sdk.tsx
Enable users to select SDK 48 in the dropdown on Snack. We've deployed and tested SDK 48 to some extent, it should be mostly ready for normal usage.
Enabled the flag.
Minor change
> chore(website): enable SDK 48 in dropdown

- runtime/src/App.tsx
- runtime/src/Files.tsx
- runtime/src/Modules.tsx
- runtime/src/NativeModules/ExpoRouterEntry.tsx
Due to us marking the `expo-router` packages as bundled, it won't pop up in Snack dependencies anymore.
Instead, we check on `import "expo-router";` in entry point.
See staging
> fix(runtime): use proper expo-router entrypoint detection

- packages/snack-require-context/src/utils/context.ts
- runtime/src/App.tsx
- runtime/src/Modules.tsx
This fixes a couple of things around the newer `require.context` implementation for Expo Router.
- Keep track of each dependent of a virtual module, invalidate only those virtual modules when dependent was changed.
- Invalidate all virtual modules whenever a new file was added
- Only flush the root component when not using `expo-router`
See staging.
> fix(runtime): improve virtual module invalidation

- .github/workflows/snackpub.yml
- snackpub/k8s/base/kustomization.yaml
- snackpub/k8s/base/pdb.yaml
- snackpub/skaffold.yaml
Snackpub deployments are currently broken.
- Fix `skaffold` commands in GHA.
- Fix cluster name.
- Removed pdb from k8s config.
Manually triggered successful deployments for [staging](https://github.com/expo/snack/actions/runs/5579453245/jobs/10195050524) and [production](https://github.com/expo/snack/actions/runs/5579549858/jobs/10195298956).
> Fix snackpub deployments

- runtime/src/Errors.tsx
- runtime/src/Files.tsx
- runtime/src/Modules.tsx
Before | After
--- | ---
[![Stack traces before this fix](https://github.com/expo/snack/assets/1203991/df291b4d-158c-48df-a6e8-a8138c8a6522)](https://github.com/expo/snack/assets/1203991/df291b4d-158c-48df-a6e8-a8138c8a6522) | [![Stack traces after this fix](https://github.com/expo/snack/assets/1203991/6f2ad60e-7287-4dc8-b851-fb9799a8a365)](https://github.com/expo/snack/assets/1203991/6f2ad60e-7287-4dc8-b851-fb9799a8a365)
- Updated code evaluation to use the newer `globalEvalWithSourceUrl` ([see this](https://github.com/facebook/react-native/pull/34319))
- Updated the error summary generator (`prettyStack`)
- Fixed an unexpected newline being generated after `applyPatch('', ...)`
See staging.
> fix(runtime): use proper evaluation and stack traces based on source maps

- snackager/skaffold.yaml
- snackpub/skaffold.yaml
- website/skaffold.yaml
Fixes [ENG-9178](https://linear.app/expo/issue/ENG-9178)
- Bumped all docker node versions to from `16.14.2` to `16.20.1`.
Deploying to staging.
> chore: bump website and snackager node versions to `16.20.1`

- snackpub/k8s/base/deployment.yaml
originally we have the http readiness endpoint from #405, but cloudrun does not well support the readinessProbe. after k8s migration, we can now integrate the http readiness check.
integrate http based liveness/readiness probes rather than tcp checks
review and let's see if that works after staging deployment
> [snackpub] integrate http liveness/readiness probe

- website/src/client/configs/defaults.tsx
This is more in line with the best practices. Users can also use libraries such as react native safe area context, but this is an out-of-the-box solution.
Dropping the `expo-constants` as default dependency, since we don't need it anymore. But, users can add it back if needed.
- Replaced `paddingTop` on container with `SafeAreaView`
- Dropped default `expo-constants` dependency
See staging.
> refactor(website): user proper `SafeAreaView` and drop `expo-constants` as default dependency

- snackpub/k8s/production/deployment-replicas.yaml
reduce the replicas to the previous number which worked great.
reduce the replicas to 3
as previous experiments, three replicas should be good enough for snackpub
> [snackpub] reduce production k8s replicas

- website/src/client/auth/authManager.tsx
- website/src/client/components/DevicePreview/AppetizeFrame.tsx
- website/src/client/components/Publish/ModalSuccessfulPublish.tsx
- website/src/client/components/UserMenu.tsx
- website/src/client/types.tsx
In order to support fetching more complex data involving user fields, we should use the GraphQL API instead of `api/v2`. Necessary for querying things like:
```
{
me {
id
username 
userExperiments {
id
enabled
experiment
}
}
}
```
In a follow-up PR we should add something like `graphql-tag` to have more robust support for the GraphQL queries 
Replace the existing `userInfo` request with an equivalent query using the GraphQL API
Run the website locally and ensure user data is loaded correctly
> feature(website): Update AuthenticationManager to get user data from the GraphQL API

- website/package.json
- website/src/client/auth/authManager.tsx
- website/src/client/components/DownloadOrbitDialog.tsx
- website/src/client/components/EditorToolbar.tsx
- website/src/client/components/EditorView.tsx
- website/src/client/components/EditorViewProps.tsx
- website/src/client/utils/orbit.ts
- yarn.lock
As a part of the new Expo Orbit project, we need to add a button to the `EditorToolbar` in order to
allow users to launch their projects with just one click using Expo Orbit.
- Add "Open with Orbit" button to the `EditorToolbar` using the `expo-orbit://` custom schema
- Adds `custom-protocol-check` dependency to determine if Expo Orbit is installed or not and prompt user to install it if necessary
- Update AuthManager to query `experiments` to determine if we should display the Orbit button 
The user HAS Obit installed and presses the "Open with Orbit" button  
https://github.com/expo/snack/assets/11707729/8146d57d-2f5a-4262-a7a4-31cd1b7f21c5
The user DOES NOT HAVE Obit installed, and presses the "Open with Orbit" button 
https://github.com/expo/snack/assets/11707729/2ea85073-56fb-4bb9-b10 …
> feature(website): add support for opening projects with Orbit

- runtime/metro.config.js
- runtime/package.json
- runtime/web/deploy-script.js
When importing assets from packages bundled with the Snack Runtime, the assets are expected to be hosted at the root of the domain. This adds the `transformer.publicPath` to tell the web export where to look up the assets.
- Added `transformer.publicPath` config option based on an env flag
- Updated `web/deploy-script.js` to enable this env flag, and move assets to the proper folders for S3 upload
See staging.
> fix(runtime): use `transformer.publicPath` with deploy workaround for asset paths on web

- packages/snack-content/src/sdks/index.ts
- runtime-shell/package.json
- runtime-shell/src/App.tsx
- runtime-shell/yarn.lock
- runtime/package.json
- runtime/src/aliases/index.tsx
- runtime/yarn.lock
This is one of the important React Navigation libraries, and should work in Snack.
- Vendored `react-native-pager-view` inside the runtimes.
See if this works on staging:
https://staging-snack.expo.dev/?platform=android&name=header%20button&dependencies=%40expo%2Fvector-icons%40*%2C%40react-native-community%2Fmasked-view%40*%2Creact-native-gesture-handler%40*%2Creact-native-pager-view%40*%2Creact-native-paper%40%5E4.7.2%2Creact-native-reanimated%40*%2Creact-native-safe-area-context%40*%2Creact-native-screens%40*%2Creact-native-tab-view%40%5E3.0.0%2C%40react-navigation%2Fbottom-tabs%406.3.1%2C%40react-navigation%2Fdrawer%406.4.1%2C%40react-navigation%2Felements%401.3.3%2C%40react-navigation%2Fmaterial-bottom-tabs%406.2.1%2C%40react-navigation%2Fmaterial-top-tabs%406.2.1%2C%40react-navigatio …
> fix: bundle `react-native-pager-view` inside the runtime to avoid Snackager errors

- website/src/client/components/EditorToolbar.tsx
- website/src/client/components/EditorView.tsx
- website/src/client/utils/detectPlatform.tsx
- website/src/client/utils/orbit.ts
Closes ENG-9990
In order to remove the need for an "Enable Orbit" option inside User Settings, we need to check if Orbit is available in the user's machine so we can automatically display the "Open with Orbit" button in the editor toolbar.
To achieve this functionality, Orbit v1 will ship with a local HTTP server that we can just fetch from the website and verify if Orbit is running. As long as Orbit is open, the "Open with Orbit" button should be displayed. 
For more context check https://github.com/expo/orbit/pull/52
This PR updates the Orbit integration to fetch the localhost server using the predetermined ports (35783, 47909, 44171, 50799) and wraps all the logic of this feature in a new hook called `useOrbit`
With Orbit running in the background …
> feature(website): Update Orbit integration to fetch local server

- .github/workflows/snackager.yml
Prefer running jobs in parallel to speed up things as much as possible.
- Added `Snackager / e2e` job to the [**snackager.yml**](./.github/workflows/snackager.yml) workflow.
- Added missing **packages/snack-require-context** to path triggers.
See CI
> refactor(snackager): clean up snackager workflow and split e2e own job

- .github/workflows/packages.yml
- .github/workflows/runtime.yml
- .github/workflows/snackager.yml
- .github/workflows/snackpub.yml
- .github/workflows/website.yml
Before this change, a manual deployment could cancel the workflow running on `main`. 
This prevents that by adding `github.event_name` to the concurrency check.
Workflow change only.
> fix: prevent workflows from auto-canceling when triggered from other sources

- .github/actions/setup-runtime/action.yml
- .github/actions/setup-snackager/action.yml
- .github/actions/setup-snackpub/action.yml
- .github/actions/setup-website/action.yml
- .github/workflows/appetize-validation.yml
- .github/workflows/packages.yml
- .github/workflows/snackager.yml
- package.json
- packages/snack-babel-standalone/package.json
- packages/snack-content/package.json
- packages/snack-eslint-standalone/package.json
- packages/snack-proxies/package.json
- packages/snack-require-context/package.json
- packages/snack-runtime/package.json
- packages/snack-sdk-legacy/package.json
- packages/snack-sdk/package.json
- packages/snack-term/package.json
- snackager/Dockerfile
- snackager/package.json
- snackager/skaffold.yaml
- snackpub/skaffold.yaml
- website/Dockerfile
- website/package.json
- website/skaffold.yaml
Upgrade from EOL to supported LTS node.
- Updated all workflows to Node `18.17.1` (current `18.x`)
- Updated all Volta definitions to `18.17.1`
- Updated all skaffold configs to `18.17.1`
See staging.
> refactor: upgrade to node to `18.17.1`

- packages/snack-sdk/example/next.config.js
when loading example project, there is an error dependency. nextjs cannot build the page and cause 404 not found.
```
event - build page: /
wait  - compiling...
warn  - ../../../node_modules/vm2/lib/compiler.js
Module not found: Can't resolve 'coffee-script' in '/Users/kudo/01_Work/Repos/expo/snack/node_modules/vm2/lib'
../../../node_modules/vm2/lib/resolver-compat.js
Critical dependency: the request of a dependency is an expression
```
pubnub has a transitive dependency to vm2 and vm2 doesn't well support webpack.
```
=> Found "vm2@3.9.13"
info Reasons this module exists
- "snack-sdk#pubnub#superagent-proxy#proxy-agent#pac-proxy-agent#pac-resolver#degenerator" depends on it
- Hoisted from "snack-sdk#pubnub#superagent-proxy#proxy-agent#pac-proxy-agent#pac-resolver#degenerator#vm2"
```
vm2 …
> [snack-sdk] fix 404 page not found in example

- packages/snack-babel-standalone/package.json
- packages/snack-babel-standalone/src/entries/eslint.ts
- packages/snack-eslint-standalone/package.json
- packages/snack-eslint-standalone/yarn.lock
- website/package.json
- yarn.lock
This fixes an issue with `snack-eslint-standalone` and `snack-babel-standalone`.
- Bumped up `snack-babel-standalone` in `snack-eslint-standalone`
- Resolved all testing issues
- Validated in website locally
- Published `snack-babel-standalone@3.0.1`
- Published `snack-eslint-standalone@2.0.0`
- `$ yarn`
- `$ yarn start`
- Open [website locally](http://snack.expo.test)
- Should not give ESLint errors
> fix(snack-babel-standalone): expose `traverse` for eslint

- snackager/k8s/base/deployment.yaml
- website/deploy/base/deployment.yaml
This reflects some manual changes I made to reduce restarts of snackager.
- Set memory limits equal to memory requests
- Unset CPU limits
Ref: https://cloud.google.com/architecture/best-practices-for-running-cost-effective-kubernetes-applications-on-gke#set_appropriate_resource_requests_and_limits
> [infra] Use best practices for resource limits

- website/src/client/components/PageMetadata.tsx
SEO request.
- Only the root of snack (`https://snack.expo.dev`) is allowed to index.
- Any nested URL that loads a Snack, e.g. `https://snack.expo.dev/@<user>/<snack>`, is blocked from crawling.
- Check if `<meta name="robots" content="all" />` is set on [staging-snack.expo.dev](https://staging-snack.expo.dev/).
- Check if `<meta name="robots" content="none" />` is set on all other URLs.
> chore(website): only allow crawling the root Snack page

- website/src/client/utils/snackTransports.tsx
- website/src/client/workers/SnackTransport.worker.tsx
snackpub was fully rolled out to production and we don't need the measurement anymore. this could save the big query cost a little bit.
revert partial code from #380 on website
ci passed
> [website] remove snackpub analytics

- website/src/client/components/EditorToolbar.tsx
- website/src/client/utils/orbit.ts
With the official release of Orbit, it should no longer be considered an experiment and should be visible to all users
Update useOrbit hook to make the Orbit button always visible 
"Open with Orbit" button should be now visible to all accounts
>    chore(website): Enable Orbit to all macOS users

- packages/snack-content/package.json
- packages/snack-content/src/defaults.ts
- packages/snack-sdk/package.json
- packages/snack-sdk/src/__tests__/__snapshots__/dependencies-test.ts.snap
- packages/snack-sdk/src/__tests__/__snapshots__/devsession-test.ts.snap
- snackager/src/__integration-tests__/__snapshots__/git.test.ts.snap
We are preparing for SDK 50, this was a left over of the previous SDK release cycle.
- Updated `snack-content` to default to SDK 49
See staging
> refactor(website): default to SDK 49

- packages/snack-sdk/src/utils.ts
Part of [ENG-11039](https://linear.app/expo/issue/ENG-11039/[runtime]-update-supported-snack-url)
See: https://stackoverflow.com/a/7111947
- Remove `!` from character list when generating channel IDs
- Update errors in `createChannel` to be more informative
See tests.
> refactor(snack-sdk): make `channel` generation URL-safe

- .gitignore
- packages/snack-runtime/src/Constants.ts
- runtime-shell/.env.example
- runtime-shell/metro.config.js
- runtime-shell/package.json
- runtime/.env.example
- runtime/app.config.js
- runtime/package.json
- runtime/src/Constants.ts
Part of [ENG-11039](https://linear.app/expo/issue/ENG-11039/[runtime]-update-supported-snack-url)
Now that we have proper environment variables support, the old system blocks more than it helps.
This replaces `require('expo-constants').manifest.extra.cloudEnv` with just `process.env.EXPO_PUBLIC_SNACK_ENV`.
This will be part of the SDK 50 release.
> refactor(runtime): drop `cloudEnv` in favor of `EXPO_PUBLIC_SNACK_ENV`

- website/src/client/utils/PlatformOptions.ts
Refs:
* https://github.com/expo/expo/pull/26351#discussion_r1447872140
Reorder preview platform tabs to match order specified in writing guidelines:
* https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md#referencing-android-ios-and-web
The chanage has been reviewed locally. All lint checks are passing.
> [website] reorder preview platform tabs

- .gitignore
- runtime/.env.example
- runtime/app.config.js
- runtime/package.json
- runtime/src/App.tsx
- runtime/src/Constants.ts
- runtime/src/Files.tsx
- runtime/src/Modules.tsx
- runtime/src/transports/RuntimeTransportImplSocketIO.ts
This removes one of the last dependents on `expo-constants` within Snack. The last remaining one is the `Constants.statusBarHeight`.
- Replaced `cloudEnv` with `EXPO_PUBLIC_SNACK_ENV`
- Added `.env.example` file
Will be included in the full SDK 50 upgrade, and tested on Staging.
> refactor(runtime): replace `cloudEnv` with `EXPO_PUBLIC_SNACK_ENV`

- runtime/metro.config.js
- runtime/package.json
This sets the right preset for node-only files in the runtime.
- Added missing `override` for `*.config.js` files.
See CI.
> chore(runtime): use right preset for `*.config.js` files

- .github/actions/setup-runtime/action.yml
- .github/workflows/runtime.yml
- runtime/package.json
- runtime/web/deploy-script.js
Starting from SDK 50, we are swapping to EAS Updates.
- Updated github workflows to deploy to EAS Update
- Updated package scripts to deploy EAS Update
TBD, staging.
> chore(runtime): update deployment workflow for eas

- packages/snack-babel-standalone/package.json
- packages/snack-babel-standalone/src/bundled.ts
- packages/snack-babel-standalone/webpack.config.js
- packages/snack-babel-standalone/yarn.lock
- runtime/src/Modules.tsx
This is a new change from 0.73, let's update accordingly.
- Updated all babel plugins
- Updated react native preset
See staging
> refactor(babel-standalone): upgrade babel and use new react native preset

- website/deploy/development/snack.env
- website/deploy/production/snack.env
- website/deploy/staging/snack.env
This was renamed, but not in the `.env` files for web.
- Updated
TBD
> chore(website): update proper env var for snack runtime

- website/src/client/utils/orbit.ts
With the new `experienceURL` format Orbit can no longer distinguish an Expo Update from an Snack just by checking the URL, because of that we should use the `/snack` route which is specific for snacks
Closes ENG-11059
Update Orbit deep link route to use `/snack`
Run snack locally and launch Orbit from the button 
https://github.com/expo/snack/assets/11707729/b4f631c6-ae79-4791-8252-2185997d0e8a
> chore(website): Update Orbit deep link route

- packages/snack-content/package.json
- packages/snack-content/src/__tests__/urls-test.ts
- packages/snack-content/src/urls.ts
- packages/snack-sdk/package.json
- packages/snack-sdk/src/utils.ts
- website/package.json
After implementing this in orbit, this change didn't make sense.
- Use the full SDK version in runtime URL helpers
See tests
> refactor(snack-content): use full sdk version in runtime url helpers

- snackager/Dockerfile
- snackager/src/utils/convertRepoToSnack.ts
- website/src/client/components/Import/ImportRepoModal.tsx
Git imports seems to fail now.
- Ensure git is available in Snackager
- Ensure files are lower than `10 * 1024 * 1024` bytes, otherwise skip file
See staging
> fix(snackager): ensure git is installed and avoid importing files over 10mb

- snackager/package.json
- snackager/src/__integration-tests__/git.test.ts
- snackager/src/utils/convertRepoToSnack.ts
- yarn.lock
Snack uses snackager to load dependencies. We should not be importing the `node_modules` when people import their git project.
- Added git e2e test to skip importing `node_modules`
- Added picomatch to filter `node_modules` files
See CI
> fix(snackager): do not import `node_modules` files when importing from git

- website/src/client/components/DevicePreview/AppetizeFrame.tsx
These overlay buttons were required in the past, as we couldn't customize these buttons. Now we can, and we should drop the buttons.
- Dropped button overlay
See staging
> refactor(website): drop overlay buttons from appetize preview

- website/package.json
- website/src/client/components/DevicePreview/AppetizeFrame.tsx
- website/src/client/components/DevicePreview/DevicePreview.tsx
- website/src/client/components/DevicePreview/MyDeviceFrame.tsx
- website/src/client/components/EditorView.tsx
- website/src/client/utils/Appetize.ts
- yarn.lock
Follow up for expo/snack#558. If we want to add device control to rotate the device, we need to allow users to resize that panel (because else it gets too small).
This introduces `react-resizable-panels` and implements it for the editor and preview. Note, for embeds, this won't be enabled.
See staging.
> feature(website): make device preview panel resizable

- .github/workflows/appetize.yml
We can now configure default devices per SDK. Since the website is loading available from Appetize, we need to ensure the configured default device is still available on Appetize.
- Updated Appetize workflow to fail when any of the configured devices is unavailable
See CI
> feature(ci): validate if configured default Appetize device is available

- website/src/client/components/DevicePreview/AppetizeDeviceControl.tsx
- website/src/client/components/DevicePreview/AppetizeFrame.tsx
- website/src/server/components/AppetizeScript.tsx
This is the final stacked PR to finalize the new Appetize integration. See #558.
<details><summary>See screenshot</summary>
</details>
- Added "reload", "shake", and "rotate" device controls
- Added icons for each individual controls
See staging.
> refactor(website): use icons for the Appetize device controls

- website/src/client/components/EditorView.tsx
Fixes #567 
- Auto shrink the editor when opening the log/error panel
See staging
> fix(website): allow log/error panel to open

- website/src/client/utils/orbit.ts
With the Orbit [Windows Preview 1](https://github.com/expo/orbit/releases/tag/expo-orbit-v2.0.0-preview.1) now available, users can run Orbit on Windows and soon will be able to run it on Linux as well.  
Update the `useOrbit` logic to: on macOS always display the "Open with Orbit" button and other other platforms check if Orbit is running and then display the button
On Windows with Orbit running in the background
On Windows with Orbit closed
> feature(website): Enable Orbit button on Windows and Linux

- .github/actions/setup-google-cloud/action.yml
- .github/workflows/snackager.yml
- .github/workflows/snackpub.yml
- .github/workflows/website.yml
I hope this will let us remove the service account key from our GitHub Actions secrets.
I was able to succesfully deploy snackager to staging, which suggests the other deployments will work too. https://github.com/expo/snack/actions/runs/8271897475/job/22632693926?pr=570
> chore(ci): Google Cloud Workload Identity Federation

- packages/snack-content/src/sdks/index.ts
- packages/snack-runtime/src/aliases/common.tsx
- runtime/src/aliases/common.tsx
- snackager/src/bundler/externals.ts
Expo modules core is importing `crypto` in one of its files, which causes Snackager to panic. This vendors `expo-modules-core` and keeps it out of Snackager's list of problems.
- Marked `expo-modules-core` as external in Snackager
- Alias `expo-modules-core` in Runtime
- Alias `expo-modules-core` in Snack Runtime (custom)
`expo-symbols` seems to be compilable by Snackager now! https://github.com/expo/snack/actions/runs/8852447955/job/24311170804
> fix: vendor `expo-modules-core` from Snack Runtime

- snackager/src/bundler/makeConfig.ts
This should fix the wrong externals that [`@react-navigation/native@7.0.0-rc.12` is getting](https://github.com/expo/snack/actions/runs/9894635109/job/27332602658#step:4:215).
- Combined legacy `.mjs` support with new `.mjs` and `.cjs` support.
- Marked modules as not fully specified (adds extensions to the imports)
See staging and:
- `$ cd ./snackager`
- `$ yarn bundle @react-navigation/native@7.0.0-rc.12 | yarn bunyan`
- Should not output extraneous externals:
> fix(snackager): avoid incorrect externals when bundling modules

- website/src/server/utils/getSplitTests.tsx
Fixes ENG-12877
Update the security settings for `snack-values`, which only contains a few global properties for the UI.
Added proper options for the cookie.
See staging.
> fix(website): use proper secured settings for `snack-values` cookie

- .github/workflows/website.yml
- website/src/client/workers/typings.worker.tsx
This is a workaround for `react-native-safe-area-context` type definitions not being able to render properly.
The original error triggered:
Which is incorrect, as `SafeAreaView` is a correct type.
- Force-mutate the loaded type definitions for `react-native-safe-area-context`
See staging
> fix(website): allow mutating type definitions for libraries to workaround legacy typescript issues

- packages/snack-sdk/src/DevSession.ts
The cost of this is getting out of hand, we need to limit the amount of `development-session/*` calls. 
After some time, the development session should automatically be invalidated. If you run into this, use the QR code instead to run Snack on your own device.
- Disabled recurrent development session notifications on the SDK (and snack.expo.dev).
See staging.
> refactor(sdk): disable recurrent development session notifications

- snackager/k8s/production/external-secret-env.yaml
- snackager/scripts/port-forward-redis
We're upgrading our Redis infrastructure.
- Updated the host IP in the `port-forward-redis` script.
- Updated the secret version for snackager env.
> [infra] Use new Cloud Memorystore host.

- snackpub/Dockerfile
The root **package.json** was recently changed to automatically bootstrap the repository when installing. This needs to be disabled in the Dockerfiles since we are doing customization of the repository when building.
- Added `--ignore-scripts` to the `yarn install` statements in Snackpub's Dockerfile
See CI
> chore(snackpub): update Dockerfile for yarn-related changes

- website/src/client/components/EditorToolbar.tsx
- website/src/client/components/EditorView.tsx
- website/src/client/components/EditorViewProps.tsx
- website/src/client/components/LoginToSaveDialog.tsx
Part of ENG-15173
Guest users should not be able to save Snacks as they would have no way to delete them.
Tested locally. The following actions open the "login to save" prompt when not logged in:
- cmd + S
- click on save
- click on download
> [website] login to save

- packages/snack-content/src/defaults.ts
- packages/snack-sdk/src/__tests__/__snapshots__/dependencies-test.ts.snap
- packages/snack-sdk/src/__tests__/__snapshots__/devsession-test.ts.snap
- packages/snack-sdk/src/__tests__/dependencies-test.ts
- snackager/src/__e2e__/__snapshots__/git.test.ts.snap
It has been long enough.
Changed default SDK to `54.0.0`
See tests and staging
> chore(snack-content): default to Expo SDK 54 when creating new snacks
